### ISSUE TITLE
License compatibility with libgit2 ?

### ISSUE THREAD

**Issue by jacquetc** [rust-lang/git2-rs#1019]
Hello,

I'm not a lawyer, so is your dual licensing "Apache License" & "MIT" compatible with the modified GPLv2 of your core library libgit2 ?

 _libgit2_ is "GPLv2 with a Linking Exception that lets you use it with open or proprietary software." (dixit [the official libgit2 website](https://libgit2.org/)). See also the file itself [here](https://github.com/libgit2/libgit2/blob/main/COPYING).

If it's compatible, wouldn't be good to precise this compatibility in the Readme with the license of _libgit2_ ?

Licenses are a mess to understand, so I hope someone in the community can clarify this blurry point ?

**Comment by joshtriplett** [comment]
GPLv2 and MIT are in general compatible already. But beyond that, libgit2's exception says:

> the authors give you unlimited permission to link the compiled version of this library into combinations with other programs, and to distribute those combinations without any restriction coming from the use of this file.

That exception means users of git2-rs will generally have no license obligations with respect to libgit2.

**Comment by jacquetc** [comment]
Thank you for your answer. I was leaning toward the same ideas, so your answer means that I didn't misread. 

Have a good day !
