### ISSUE TITLE
Question about maintainers

### ISSUE THREAD

**Issue by vcfxb** [rust-lang/git2-rs#1070]
Hello! 

I wanted to ask who is maintaining this project and if I could potentially join the list of maintainers/authors?

**Comment by ehuss** [comment]
Hi! Thanks for your interest in helping with this project. We normally only add people after they have been involved with the project for a while. We also don't have the structure set up to independently add new maintainers, as this is maintained by the cargo team.

If you are interested, you can help with trying to review PRs, triage or respond to issues. Fixing small bugs, or improving tests is often a good way to get started. I see that you have a couple PRs opened recently, and I can try to respond to them, but overall I'm uncertain about moving forward with them at this time.

**Comment by vcfxb** [comment]
Thank you for your response -- that makes sense 👍
