### ISSUE TITLE
`fetch_options` in `RepoBuilder` receives immutable variable, but `remote_callbacks` of `FetchOptions` returns mutable variable

### ISSUE THREAD

**Issue by AspadaX** [rust-lang/git2-rs#1080]
As I followed the instructions in the documentation, I found that in the release that I added to my project, which is `v0.19.0`, `RepoBuilder` does not receive the value type returned by `FetchOptions`. 

Is this an issue? Or I misunderstood the documentations or the usage? Below is my code snippet for the part that I stumbled on: 
```
// prepare to process callbacks
let mut callbacks = RemoteCallbacks::new();

// set a remote `fetch_option` for processing callbacks from the remote git
// the fetch options is always a mut even after I removed the `mut` keyword
let mut fetch_options = FetchOptions::new()
    .remote_callbacks(callbacks);

let repository = RepoBuilder::new()
    .fetch_options(fetch_options)
 .clone(
   &url,
     &working_directory
  )?;
```

Thanks for looking into this!

**Comment by ehuss** [comment]
To use `FetchOptions` as a value, you can't use method chaining like that. You'll need to do something like:

```rust
    let mut fetch_options = FetchOptions::new();
    fetch_options.remote_callbacks(callbacks);
```

**Comment by AspadaX** [comment]
> To use `FetchOptions` as a value, you can't use method chaining like that. You'll need to do something like:
> 
> ```rust
>     let mut fetch_options = FetchOptions::new();
>     fetch_options.remote_callbacks(callbacks);
> ```

now it works. thank you so much!
