### ISSUE TITLE
Unable to retrieve objects replaced by `git-replace`

### ISSUE THREAD

**Issue by orhun** [rust-lang/git2-rs#1081]
### Description

`git2` does not return the new values for objects replaced via `git-replace` command.

### Reproduce steps

```bash
cd $(mktemp -d)
git init .
git commit --allow-empty -m 'test: test commit'
```

`log` example works fine:

```sh
$ cargo run --example log -- --git-dir /tmp/<path>

commit 37c00d39b18b49ae5819b798b2b3256b4169223b
Author: Orhun Parmaksız <orhunparmaksiz@gmail.com>
Date:   Sun Sep  1 15:25:43 2024 +0300

    test: test commit
```

Then edit the last commit via [`git-replace`](https://git-scm.com/docs/git-replace):

```sh
git replace --edit HEAD # e.g. change "test" -> "best"
```

`log` example still shows the old commit message:

```
$ cargo run --example log -- --git-dir /tmp/<path>

commit 37c00d39b18b49ae5819b798b2b3256b4169223b
Author: Orhun Parmaksız <orhunparmaksiz@gmail.com>
Date:   Sun Sep  1 15:25:43 2024 +0300

    test: test commit
```

Whereas `git log` command shows the replaced commit message (it also says "replaced")

```
$ git log

commit 37c00d39b18b49ae5819b798b2b3256b4169223b (HEAD -> master, replaced)
Author: Orhun Parmaksız <orhunparmaksiz@gmail.com>
Date:   Sun Sep 1 12:25:43 2024 +0300

    test: best commit
```

### Additional context

Please see https://github.com/orhun/git-cliff/issues/826

> Presumably an extra lookup query needs to happen for every object used to get the replacements (if any).

**Comment by weihanglo** [comment]
It seems like the upstream libgit2 does not yet support it: https://github.com/libgit2/libgit2/issues/1730

**Comment by ehuss** [comment]
Thanks! Yea, closing as this looks like an upstream issue.

**Comment by orhun** [comment]
See you guys in another 10 years 😄
