### ISSUE TITLE
Build failure when pulled in via cargo-outdated

### ISSUE THREAD

**Issue by MaxG87** [rust-lang/git2-rs#1092]
I try do define a Rust base image to be used in several CI pipelines. This is what a MWE looks like:

```dockerfile
ARG RUST_VERSION
FROM rust:${RUST_VERSION}-slim-bullseye

# The Rust base images seem to be created only once. Thus, in order to prevent
# using outdated packages, we need to update the image.
RUN apt update \
    && apt full-upgrade -y \
    && apt install -y curl git libssl-dev pkg-config \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-outdated
```

Note that I install `curl` and `git` via `apt`. Before adding `curl` the container build fine. After adding `curl` I got the following error message:

```
100.7    Compiling git2-curl v0.19.0
101.6 error[E0425]: cannot find value `__deserializer` in this scope
101.6    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-0.76.0/src/cargo/core/features.rs:734:32
101.6     |
101.6 734 |     #[serde(deserialize_with = "deserialize_build_std")]
101.6     |                                ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
101.6
108.8 For more information about this error, try `rustc --explain E0425`.
108.8 error: could not compile `cargo` (lib) due to 1 previous error
108.9 error: failed to compile `cargo-outdated v0.15.0`, intermediate artifacts can be found at `/tmp/cargo-installMAtqaR`.
108.9 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
------
Dockerfile:12
--------------------
  10 |         && rm -rf /var/lib/apt/lists/*
  11 |
  12 | >>> RUN cargo install cargo-outdated
  13 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cargo install cargo-outdated" did not complete successfully: exit code: 101
```

I find that puzzling and wanted to report the bug here. If you think the responsibility is with `cargo-outdated`, let me know. I'll open the ticket there.

**edit:** I forgot to add that this error appears when setting `RUST_VERSION=1.82.0`.

**Comment by weihanglo** [comment]
Which version of 
* curl
* Rust toolchain
* cargo-outdated
you were using or installing?

**Comment by ehuss** [comment]
This does not look related to `git2`. The error is coming from building cargo-0.76.0 (which is quite an old version).

**Comment by MaxG87** [comment]
Thank you for the replies so far.

How can cargo be outdated if I am using the most recent Rust image? [1.82-slim-bullseye](https://hub.docker.com/layers/library/rust/1.82.0-slim-bullseye/images/sha256-1a9d9534f07bbbda6370e28d3039a35e50b698fa42e6f4cfad4f21281e9a91bf?context=explore) was published only four days ago.

**Comment by MaxG87** [comment]
Thank you for the hint. I will move this to `cargo-outdated`.
