### ISSUE TITLE
Feature request: Tree::get_subtree

### ISSUE THREAD

**Issue by russkel** [rust-lang/git2-rs#1097]
Hello,

I think this function is missing from the bindings: https://libgit2.org/libgit2/#v0.17.0/group/tree/git_tree_get_subtree

I am writing some tooling to do semantic release analysis on mono-repos and I think this would be an efficient way to get the tree for the package directories.

I would have an attempt to implement it myself but I am far too green with Rust at this point.

**Comment by russkel** [comment]
Oh I see this is in version `1.16.0` which is quite a bit beyond the version referenced in the repo README.

**Comment by weihanglo** [comment]
Is that still a thing in the latest libgit2 C library? The doc you provided is libgit2 0.17.0, which [is pretty old (2012)](https://github.com/libgit2/libgit2/releases/tag/v0.17.0) and predates Rust 1.0.

libgit2 1.8 doesn't seem to have any subtree concept in its API. Also, from my understanding, `git subtree` is just some manipulation on git tree object for under a certain directory. I think you are able to get your own “subtree” by identifying a [`git2::Tree`](https://docs.rs/git2/latest/git2/struct.Tree.html) of a path.

**Comment by russkel** [comment]
> Is that still a thing in the latest libgit2 C library? The doc you provided is libgit2 0.17.0, which [is pretty old (2012)](https://github.com/libgit2/libgit2/releases/tag/v0.17.0) and predates Rust 1.0.

You're right, I goofed with the google search result of the old libgit version.

I think this is the way it is done now:

```rust
    let tree = head.peel_to_tree().unwrap();
    let subtree_entry = tree.get_path(packages_path).unwrap();
    let subtree = subtree_entry.to_object(repo).unwrap().peel_to_tree().unwrap();
```

Apologies for wasting your time.

**Comment by weihanglo** [comment]
No worries. Glad it helps!
