### ISSUE TITLE
unstage file

### ISSUE THREAD

**Issue by harilet** [rust-lang/git2-rs#1104]
I was trying to unstage files. I can add file fine by using

```
let mut index = repo.index().unwrap();
index.add_path(Path::new(&path)).unwrap();

```

I saw we can use the remove_path like this

```
let mut index = repo.index().unwrap();
index.remove_path(Path::new(&path)).unwrap();
index.write().unwrap();
```

but this deletes file not remove changes
![Image](https://github.com/user-attachments/assets/de5b71dd-6882-49d7-9c0d-bf2750a90344)

what can I do?
and I saw this remove but the 2th parameter stage is an int but have no more detail
https://docs.rs/git2/latest/git2/struct.Index.html#method.remove

**Comment by ehuss** [comment]
The 2nd parameter is usually 0 for the main index. Other numbers are used when dealing with merge conflicts and such.

**Comment by harilet** [comment]
@ehuss ok I understand that now.

so what can I do to just unstage changes from a file, any ideas?

**Comment by harilet** [comment]
@ehuss 
similar to remove_path remove also just deletes the file from the index not unstage the changes

```
let mut index = repo.index().unwrap();
index.remove(Path::new(&path),0).unwrap();
index.write().unwrap();
```

output
![Image](https://github.com/user-attachments/assets/cacf82bf-d40b-4291-94f4-76103506e656)

**Comment by harilet** [comment]
@ehuss I got it, the first method worked thanks
