### ISSUE TITLE
Cannot clone using ed25519 key on Windows while the same code and key work fine on Linux

### ISSUE THREAD

**Issue by daltongd** [rust-lang/git2-rs#1106]
Hi, I can't make the ed25519 keys work when cloning on Windows. All operations other than clone work fine, I've tried pulling, committing + pushing with 100% success rate, but when cloning I get this error:
```bash
Error: Git(Error { code: -1, klass: 23, message: "failed to start SSH session: Unable to exchange encryption keys" })
```

Crate version from Cargo.toml:
```toml
git2 = "0.19.0"
```

I've tried many different things together with converting my keys to PEM as suggested here: [#659](https://github.com/rust-lang/git2-rs/issues/659), unfortunately those are no longer supported.

I looked for any outdated libssh versions in the dependencies, since I've seen a few past comments mentioning updating their dependencies helped solve similar problems, but no luck here.

I've tried using the `auth-git2` crate, as well as this code:
```rs
let mut repo_builder = git2::build::RepoBuilder::new();
let mut fetch_options = git2::FetchOptions::new();
let mut remote_callbacks = git2::RemoteCallbacks::new();

remote_callbacks.credentials(|_, _, _| {
    let credentials = git2::Cred::ssh_key(
        "git",
        Some(Path::new("HOME_PATH/.ssh/id_ed25519.pub")),
        Path::new("HOME_PATH/.ssh/id_ed25519"),
        None,
    )
    .expect("Could not create credentials object");

    Ok(credentials)
});
fetch_options.remote_callbacks(remote_callbacks);
repo_builder.fetch_options(fetch_options);

let _ = repo_builder.clone(url, &target_path.join("../test"))?;
```

I even tried copying the keys that worked on my Linux machine, but with no results. (I of course changed the paths on both platforms to the correct ones and made sure there are no mistakes by printing the file contents and comparing with what I expected to see).

All git operations work just fine when I'm using git from CLI.

All of the above failed only on Windows and only when attempting to *clone* a repo. The same setup works on Linux like a charm.

Any ideas what else I could check? I would really love to make this thing work and I'm happy to provide all the info necessary.

**Comment by daltongd** [comment]
I just tried calling `cargo install --git ssh://git@path.to:private/repo.git` and got an identical result. To my best knowledge, `cargo` also uses this crate internally, so it looks like a bug, and not a mistake on my end or an intended behavior. Could be a configuration problem, but I can't quite figure out what could be wrong with my setup. I tried on another Windows machine and the results are identical.

```bash
error: failed to clone into: [home dir]\.cargo\git\db\[crate name]-06c804456fc504ca

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to start SSH session: Unable to exchange encryption keys; class=Ssh (23)
```

### I found a workaround
I made both `cargo install` and cloning work on Windows by using the `https://path.to/private/repo.git` instead, so I'll be using this approach for now.

**Comment by ehuss** [comment]
Unfortunately I think this is a limitation of the WinCNG backend of libssh2. You can maybe try to set the `openssl-on-win32` feature on the `ssh2` crate assuming you have an environment capable of using or building openssl.

**Comment by daltongd** [comment]
Thanks, I'll give it a go soon

**Comment by daltongd** [comment]
Ok, I tested the suggested solution and it worked, thank you, @ehuss!
I also learned a valuable lesson that you can enable a feature in a dependency of your dependency as it seems. I'm not using ssh2 directly in my crate, so I was a little skeptical at first.

Since I haven't found any useful info about it, for those having similar problems - the overall solution was to:
1. Add ssh2 with `openssl-on-win32` feature as a dependency
    ```toml
    [dependencies]
    # ...
    ssh2 = { version = "0.9.4", features = ["openssl-on-win32"] }
    ```
2. Set up openssl on Windows. I struggled with this setup for a bit, so here is how I made it work
    - install openssl, e.g. from [slproweb.com](https://slproweb.com/products/Win32OpenSSL.html)
    - clone `https://github.com/microsoft/vcpkg` and run `.\scripts\bootstrap.ps1 -disableMetrics` from within the cloned repo
    - install static openssl libraries using vcpkg: `vcpkg install openssl:x64-windows-static` (from within the same directory as above, or add vcpkg to your path)
    - put this root cert: https://curl.se/ca/cacert.pem somewhere in your system e.g. `C:/certs/cacert.pem`
    - you can now set up some environment variables, for example in your powershell `$profile` or just for the current session:
    ```ps1
    $Env:VCPKG_ROOT = 'C:\path\to\your\vcpkg'
    $Env:OPENSSL_NO_VENDOR = 1
    $Env:RUSTFLAGS = '-Ctarget-feature=+crt-static'
    $Env:SSL_CERT_FILE = 'C:\certs\cacert.pem'
    ```

This should be enough of a setup, but I may have had some preexisting dependencies on my system, so your milage may vary.

I decided to make this optional, so I can install my tool by using `cargo install --git ...` on machines that don't have the whole openssl setup. For example:

In `Cargo.toml`:
```toml
[features]
openssl-on-win32 = ["dep:ssh2"]

[dependencies]
# ...
ssh2 = { version = "0.9.4", optional = true, features = ["openssl-on-win32"] }
```

Then it can be used by adding `--features openssl-on-win32` to `cargo build`, `cargo run` or `cargo install`, etc.
I hope this helps someone in the future.
