### ISSUE TITLE
Please provide examples of `git pull` and/or `git merge origin/master`.

### ISSUE THREAD

**Issue by futursolo** [rust-lang/git2-rs#129]
I want to implement the `git pull` in my program. Now I am able to implement the `git fetch`. But I cannot implement the `git merge origin/master` since there's no clear instructions indicates how to do so.

Can you add some examples about the `git pull` and/or `git merge origin/master`?

**Comment by alexcrichton** [comment]
I think that `git pull` is mostly just a fetch followed by a merge (or rebase, depending on what you're configured to do), and the entry point for merging I believe is [`Repository::merge`](http://alexcrichton.com/git2-rs/git2/struct.Repository.html#method.merge). That being said having examples would certainly be useful!

**Comment by frewsxcv** [comment]
Here's my use case:

* I'm very familiar with using git from the terminal
* I'm _not_ familiar with all the git terminology (Oid, refspec, commitish, refnames, etc.)
* I'm _not_ familiar with the underlying file structure of `.git/` and any of the files in there
* I have a Rust program I'm writing and want to replicate git commands like `git clone` and `git fetch`, but that requires me to know terminology/internals, so I either have to learn a bunch of new concepts or just shell out to the git CLI

Having docs that demonstrate how to replicate common git commands could be helpful in the README or crate level documentation. If I had more time, I'd open a PR but I'm a bit busy right now. To make this a little constructive, here's a couple commands I needed earlier today that took me a bit of time to figure out that would be good to add to this proposed documentation:

## `git fetch origin master`

```rust
let repo = git2::Repository::discover(REPO_PATH)?;
let mut origin_remote = repo.find_remote("origin")?;
origin_remote.fetch(&["master"], None, None)?;
```

## `git reset --hard origin/master`

```rust
let repo = git2::Repository::discover(REPO_PATH)?;
let oid = repo.refname_to_id("refs/remotes/origin/master")?;
let object = repo.find_object(oid, None).unwrap();
repo.reset(&object, git2::ResetType::Hard, None)?;
```

**Comment by kamalmarhubi** [comment]
@frewsxcv 
1. those docs should definitely exist!
2. that sounds like a great idea for a crate on top of git2!

**Comment by alexcrichton** [comment]
I'm gonna close this for now since this is quite old and we don't have a ton of time to handle this, but PRs to add examples are always welcome!

**Comment by zaphar** [comment]
I have added a pull request for this after muddling through the dark to implement a pull request example myself: https://github.com/rust-lang/git2-rs/pull/427

It may or may not be suitable for purpose.
