### ISSUE TITLE
Please provide bindings for the rebase API

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/git2-rs#146]
See https://libgit2.github.com/libgit2/#HEAD/search/rebase .

Since the rebase API uses annotated commits, it would also help to have bindings to the other functions that create annotated commits, including [`git_annotated_commit_lookup`](https://libgit2.github.com/libgit2/#HEAD/group/annotated/git_annotated_commit_lookup) and [`git_annotated_commit_from_revspec`](https://libgit2.github.com/libgit2/#HEAD/group/annotated/git_annotated_commit_from_revspec).

**Comment by alexcrichton** [comment]
Sounds all good to me! Just waiting on an implementation :)

**Comment by alexcrichton** [comment]
Currently tracking unimplemented APIs from libgit2 in this issue tracker, so I'm going to close this. PRs to add more support are of course always welcome!
