### ISSUE TITLE
Please export the GIT_FILEMODE_* constants

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/git2-rs#152]
libgit2-sys defines the `GIT_FILEMODE_*` constants, such as `GIT_FILEMODE_BLOB` and `GIT_FILEMODE_COMMIT`, but git2-rs does not export these.

I don't think it makes sense to make these bitflags; I think const values of type u32 would make more sense, to allow passing them directly as u32 arguments or struct fields.

**Comment by alexcrichton** [comment]
Hm this is where I'd really rather fix things as flags or constants like this are very non-idiomatic in Rust right now, perhaps we could have accessor methods for now on `IndexEntry`? (that's the struct in question?)

**Comment by joshtriplett** [comment]
`IndexEntry`, `TreeEntry`, and `TreeBuilder`, at least.  `TreeEntry::filemode_raw()` needs to continue returning a `u32`, even if `filemode()` could normalize to an enum.  In the other direction, `IndexEntry` and `TreeBuilder` could take an enum, if you don't mind preventing the creation of non-standard entries (which seems fine).

So yes, this could use a small `enum` of all the canonical values.

**Comment by alexcrichton** [comment]
Ah that's unfortunate. I'd probably prefer an enum for now with perhaps some accessor methods then?

We could also have a `__Nonexhaustive` variant to "prevent exhaustive matching"

**Comment by joshtriplett** [comment]
@alexcrichton An enum with exhaustive matching should work fine for everything except `TreeEntry::filemode_raw()`, which needs to continue returning a u32.

**Comment by alexcrichton** [comment]
Hm could that continue to return a u32 and all other methods return and work with an enum? I'd have to refresh myself where this is all used...

**Comment by joshtriplett** [comment]
@alexcrichton Yes, that will work fine. And if you make it a `bitflags!` enum, then that makes it easy to use as a u32 if needed.

**Comment by alexcrichton** [comment]
I think this is now configured as bitflags, so closing.
