### ISSUE TITLE
Please provide an example how to commit

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang/git2-rs#155]
I fail really hard to find out how to commit. Maybe I'm too dump, I don't know. Would be nice if you could provide an example!

**Comment by alexcrichton** [comment]
Certainly! It may take some time to flesh out a proper example, but in the meantime this example from Cargo may suffice:

https://github.com/rust-lang/cargo/blob/9ef9bd7a56fad605f8fe9262fc0c1f61d136cc08/tests/cargotest/support/git.rs#L112

**Comment by matthiasbeyer** [comment]
Besides that it would be wonderful if you could have a look at the code from https://github.com/matthiasbeyer/imag/pull/486/files#diff-88d3e4990ceedb0187db3c65791bcf96R95 until line 170 - if you don't mind of course - I fear that it is overly complex what I do there...

**Comment by alexcrichton** [comment]
Functionality-wise that looks good, although I might recommend more usage of `try!` vs lots of `and_then`, as I think it'd help improve readability

**Comment by DoumanAsh** [comment]
@matthiasbeyer  If it will be useful i made for myself amend\commit https://github.com/DoumanAsh/lazy-git-ext/blob/master/src/lib.rs#L164-L184

**Comment by alexcrichton** [comment]
I'm gonna close this since there's various examples throughout the ecosystem now, but a direct example here would always be welcome to get added in a PR!
