### ISSUE TITLE
Please provide a binding for git_repository_detach_head

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/git2-rs#156]
Current libgit2 provides a function `git_repository_detach_head` to detach HEAD at the current point, without having to retrieve it and then set it.  Please consider providing a binding to this function.

**Comment by alexcrichton** [comment]
Currently tracking unimplemented APIs from libgit2 in this issue tracker, so I'm going to close this. PRs to add more support are of course always welcome!
