### ISSUE TITLE
libgit2-sys is looking up iconv in /opt but git2 only searches system folders

### ISSUE THREAD

**Issue by learnopengles** [rust-lang/git2-rs#180]
Re: https://github.com/rust-lang/cargo/issues/3538

I get the following linker error when compiling anything that depends on libgit2-sys:

the linker error:

```
 = note: Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _git_path_iconv in liblibgit2_sys-ce5bbe4559aebb33.rlib(path.c.o)
     (maybe you meant: _git_path_iconv_init_precompose, _git_path_iconv , _git_path_iconv_clear )
  "_iconv_close", referenced from:
      _git_path_iconv_clear in liblibgit2_sys-ce5bbe4559aebb33.rlib(path.c.o)
  "_iconv_open", referenced from:
      _git_path_iconv_init_precompose in liblibgit2_sys-ce5bbe4559aebb33.rlib(path.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here is my config:

macOS 10.12.2
Xcode 8.2.1
git version 2.10.1 (Apple Git-78)
CMake and openssl installed via MacPorts.

Example: 

sudo port install cmake
sudo port install openssl
export OPENSSL_INCLUDE_DIR=/opt/local/include
export OPENSSL_LIB_DIR=/opt/local/lib
cargo clean
cargo install dinghy

---

When compiling the C code for libgit2-sys-0.6.6:
-- Found Iconv: -L/usr/lib -liconv

Then when running rustc on libgit2-sys-0.6.6/lib.rs:

-L native=/opt/local/lib

Where there is also an iconv.

The user can fix this by forcing git2 to search /opt/local as follows:

CMAKE_PREFIX_PATH=/opt/local/ cargo build

However, this is decidedly not user-friendly nor easily googleable (well, now it might be).

**Comment by nickolay** [comment]
Ah, apparently openssl-sys is not the only one adding macports to the library search path, [ncurses-rs does it too](https://github.com/jeaye/ncurses-rs/blob/master/build.rs). Will doing what it does - running `pkg_config` and using the include directory - fail in a different, yet painful way?

**Comment by alexcrichton** [comment]
I'm going to close this since this isn't something that this library itself has tons of control over unfortunately.

**Comment by crlf0710** [comment]
Just meet exactly this error today. My solution is install `libgit2` with macports, and then set the environment variable `LIBGIT2_SYS_USE_PKG_CONFIG=1` so this crate will pick it up.

**Comment by davidbailey00** [comment]
Copy of my comment https://github.com/rust-lang/git2-rs/issues/263#issuecomment-781741931 since this issue is also relevant:

> I think this should be re-opened as I've also encountered the issue when attempting to install `cargo-edit` and `cargo-outdated` on macOS Big Sur, with `libiconv` installed via MacPorts.
>
> Setting `RUSTFLAGS` as suggested in https://github.com/rust-lang/git2-rs/issues/263#issuecomment-510708093 did not work for me since this version of macOS does not provide `/usr/lib/libiconv.a` however the following workaround was successful: https://stackoverflow.com/a/34140282/4247209

Also, installing `libgit2` and setting `LIBGIT2_SYS_USE_PKG_CONFIG=1` did not fix the issue.

**Comment by davidbailey00** [comment]
Ah: 

> According to the macOS Big Sur 11 Beta Release Notes, "the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem."

from https://lapcatsoftware.com/articles/bigsur.html

I presume this would explain why the problem has arisen again on macOS 11 after it was previously fixed
