### ISSUE TITLE
Cherrypick bindings?

### ISSUE THREAD

**Issue by aergonaut** [rust-lang/git2-rs#181]
I'm interested in using `git2` to make a CLI tool for my team to automate some repetitive Git work we have to do. One of the main things we do a lot is cherrypicking a given revision to a bunch of different branches. I noticed that the `libgit2-sys` crate has some constants related to cherrypicking, but no bindings for the cherrypick functions themselves.

I'd love to add these, but I'm not 100% sure how to integrate them into the library. Is there a good module that I could look at for examples, or can someone provide some guidance? Thanks!

**Comment by alexcrichton** [comment]
I'd love to include this! The steps would look like:

1. Add definitions to the sys crate
2. Run `cargo run` in the `systest` folder to verify your additions are correct
3. Add `src/cherrypick.rs`, and add relevant Rust bindings.

The various modules already existing should help guide you in how to export APIs and such, but let me know if you need any help!

**Comment by promethe42** [comment]
@alexcrichton any news on this feature?

**Comment by alexcrichton** [comment]
Not currently!

**Comment by alexcrichton** [comment]
Currently tracking unimplemented APIs from libgit2 in this issue tracker, so I'm going to close this. PRs to add more support are of course always welcome!
