### ISSUE TITLE
Allow simultaneous access to multiple hunks/lines from a patch

### ISSUE THREAD

**Issue by wabain** [rust-lang/git2-rs#189]
Currently the wrappers around `git_patch_get_hunk` and `git_patch_get_line_in_hunk` mutably borrow the `Patch`. This makes it impossible to access more than one hunk or line at a time, which seems overly conservative since the libgit2 APIs don't (currently) expose any way to mutate hunks or lines. The wrapper around `git_patch_get_delta` immutably borrows the `Patch` so it seems like that might be the way to go for the other wrappers as well.

I'm happy to file a pull request to implement something around this, given guidance on the right approach to backwards/forwards compatibility.

**Comment by alexcrichton** [comment]
Most of the `&mut` decisions were largely done to be conservative, but if the source code is checked and nothing behind the scenes is changing, sounds good to me to change it to `&self`!

**Comment by alexcrichton** [comment]
This is currently done in the thinking that it's necessary for safety, but if an investigation is done to determine it's too strict then a PR can be sent to update this!
