### ISSUE TITLE
Errors returned from functions may be incorrect

### ISSUE THREAD

**Issue by lilyball** [rust-lang/git2-rs#191]
It looks like libgit2 frequently forgets to set the last error, but this library always asks libgit2 for its last error whenever any call returns an error. This means the reported error will be incorrect if libgit2 didn't call `giterr_set()`.

As an example, `revparse_ext()` apparently doesn't call `giterr_set()` for most errors, so it's easy to get bad errors from that.

Here's a short program that tries to resolve `@{-10}`, then fetches a key from config that shouldn't exist, and then tries to resolve `@{-10}` again. If you run it in a brand new repo with one commit (one where `@{-10}` shouldn't be expected to resolve), you get the following output:

```
Error resolving @{-10}: an unknown error occurred
Error finding config entry: config value 'color.badkey' was not found
Error resolving @{-10}: config value 'color.badkey' was not found
```

Note how the config error got repeated on the second revparse.

Program:

```rust
extern crate git2;

use std::error::Error;
use git2::Repository;

fn revparse(repo: &Repository) {
    match repo.revparse_ext("@{-10}") {
        Ok(_) => { println!("@{{-10}} resolved"); }
        Err(err) => { println!("Error resolving @{{-10}}: {}", err.description()); }
    }
}

fn main() {
    let repo = Repository::open_from_env().expect("can't find repo");
    let config = repo.config().expect("couldn't get config");
    revparse(&repo);
    match config.get_entry("color.badkey") {
        Ok(_) => { println!("found entry for color.badkey"); }
        Err(err) => { println!("Error finding config entry: {}", err.description()); }
    }
    revparse(&repo);
}
```

This was reproduced with git2 0.6.4.

**Comment by alexcrichton** [comment]
Whelp!

We should probably just clear the error before we call into git2 functions and then read it off afterwards to see what happened.

**Comment by kballard** [comment]
That would just turn these errors into "an unknown error occurred". The actual error value returned from the function seems to be meaningful, so why can't we just use that directly?

**Comment by alexcrichton** [comment]
Oh if we're throwing away error information we should definitely not do that! IIRC libgit2 was sometimes inconsistent about this, but I may have just misread the docs in a few places.

**Comment by kballard** [comment]
I admittedly don't have much experience with libgit2, but the few calls I've investigated are indeed returning meaningful error codes. It's certainly possible that some calls simply return `-1` on error, but the only ones I've seen so far that do that are internal calls rather than public API.

**Comment by alexcrichton** [comment]
I think this is probably an issue for libgit2 rather than this repository, so I'm going to close this issue.
