### ISSUE TITLE
Ensure that mutable borrows are always specified when needed

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/git2-rs#196]
Many methods in the various public stucts exported by `git2-rs` (such as `Repository#remote`) end up mutating one ore more underlying `libgit2` objects without taking a `&mut self` reference. This is normally fine, since `libgit2` methods usually return copies of the internal repository state. For example, `Repository#find_remote` can still be used after a call to `Repository#remote_delete`.

However, it's possible that not all `libgit2` structures alter the source data (which they were copied from) has been modified or deleted from the root `Repository`. It might be useful to have (public-facing?) documentation for such methods explaining why a mutable self reference is not required.

**Comment by alexcrichton** [comment]
Yeah lots of the structs in C I believe are akin to something like `Arc<RefCell>` in the sense that they allow aliasing via reference counting and don't require mutable access. Note that most of the structures (I don't think any?) are `Sync`, so there's no worry about concurrent access.

In general It's somewhat difficult to extract the right mutability and whatnot while also  having the rust version be usable (as C isn't as strict as Rust is). Did you find a specific problem, though? If something is segfaulting that's very bad!

**Comment by Coneko** [comment]
I found myself stuck on the opposite problem while trying to put both a `Repository` and a `Remote` in the same `struct` using `rental`.

Why does `Remote` require a `&mut self` reference for methods that mutate the underlying `Repository`? `Repository` itself doesn't require it when updating head for example. At first I thought methods used mutable references or not depending on whether the underlying C function used a const pointer or not, but that's not the case.

Is `mut` being used to ensure thread safety? The mention above about `Sync` seems to imply that's not the case.

I'm trying to understand this to find out whether certain mutable references can be changed to immutable references.

**Comment by alexcrichton** [comment]
The usage of `mut` may have been overly conservative. I agree that if types aren't `Sync` it's likely fine to remove the `mut` requirement!

**Comment by alexcrichton** [comment]
I'm going to close this since IIRC most APIs should be appropriately conservative today, but there are problems then an issue can certainly be opened!
