### ISSUE TITLE
Worktree support?

### ISSUE THREAD

**Issue by buster** [rust-lang/git2-rs#203]
Is support for worktrees planned in this crate? I see that there has been some work merged in libgit2: https://github.com/libgit2/libgit2/pull/3436 but i don't find documentation for this in git2-rs...

**Comment by alexcrichton** [comment]
Not necessarily planned per se, but PRs are of course always welcome! I see no reason to *not* support it!

**Comment by asayers** [comment]
This crate has some support for worktrees as of 4f682bd3a4f7ef0c6546bd9f91e1afe574e24d40. Eg. `Repository::discover(path)` now works correctly when `path` points to a worktree.

@alexcrichton This is pretty useful; are you planning a release soon?

**Comment by kaendfinger** [comment]
Working on improving this in my fork.

**Comment by alexcrichton** [comment]
I'm gonna close this since we're not currently tracking unimplemented APIs, but PRs to implement are always welcome!
