### ISSUE TITLE
Pull Implementation?

### ISSUE THREAD

**Issue by rylio** [rust-lang/git2-rs#211]
Would it be in the scope of this project to add an implementation of `git pull`? It isn't a libgit2 binding, but it is useful.

**Comment by alexcrichton** [comment]
Thanks for the report! I think there's some pull-related bindings in here (in the sense that crates.io and Cargo are pulling git repos). Could you detail a bit more what you're thinking here? In general I'd personally prefer to stick as close as possible to libgit2 and let external libs build further apis and such.

**Comment by rylio** [comment]
I was thinking something similar to the implementation in [objective-git](https://github.com/libgit2/objective-git/blob/master/ObjectiveGit/GTRepository%2BPull.m).

**Comment by alexcrichton** [comment]
Hm that seems pretty well contained actually, seems reasonable to me!

**Comment by mitchtbaum** [comment]
> there's some pull-related bindings in here (in the sense that crates.io and Cargo are pulling git repos)

[crates.io's fetch and reset --hard](https://github.com/rust-lang/crates.io/blob/57562fdb4760b2351cc8fd89bfca87e06941c978/src/git.rs#L197-L201)
(confimed by, [`What is the difference between git pull and git reset --hard origin/<branch>?`](https://stackoverflow.com/questions/43037293/what-is-the-difference-between-git-pull-and-git-reset-hard-origin-branch))

**Comment by alexcrichton** [comment]
I'm gonna close this since we're not currently tracking unimplemented APIs, but PRs to implement are always welcome!
