### ISSUE TITLE
Support includeIf config option

### ISSUE THREAD

**Issue by huntiep** [rust-lang/git2-rs#217]
This is a feature added in git 2.13. Support in libgit2 is being worked on, it might not require any changes here. The tracking issue is [here](https://github.com/libgit2/libgit2/issues/4246) and the pull request is [here](https://github.com/libgit2/libgit2/pull/4244).

**Comment by alexcrichton** [comment]
We're not currently tracking unimplemented APIs here in the issue tracker but PRs are of course always welcome to add more bindings!
