### ISSUE TITLE
ODB backend support?

### ISSUE THREAD

**Issue by eternaleye** [rust-lang/git2-rs#222]
libgit2 supports implementing custom ODB (Object Database) backends, which can be used to store git's underlying data in [databases](https://github.com/libgit2/libgit2-backends), cloud [storage systems](https://www.slideshare.net/MinqiPan/how-we-scaled-git-lab-for-a-30k-employee-company), or other ways of storing the actual object data.

It'd be _incredibly_ cool if we could write backends of that sort in Rust!

**Comment by alexcrichton** [comment]
I'd definitely be up for supporting this, and it might likely end up looking very similar to [how transports look today](https://github.com/alexcrichton/git2-rs/blob/master/src/transport.rs)

**Comment by kaendfinger** [comment]
I'm looking at this currently, along with my work in #277

**Comment by kamalmarhubi** [comment]
@kaendfinger any update on odb / refdb / config backends? If not, I was about to start on odb and refdb at least.

**Comment by alexcrichton** [comment]
I think https://github.com/alexcrichton/git2-rs/pull/277 added some more bindings, but there's probably still some more left!

Adding a custom backend tends to be pretty tricky as "done right" I think it goes through an implementable trait in Rust (like the transports today), but should certainly be possible!

**Comment by kamalmarhubi** [comment]
Yeah, I was thinking a trait for those. Will start looking at this this week.

**Comment by kamalmarhubi** [comment]
@alexcrichton could you rename this issue to include the word ‘backend’ in its title?

**Comment by alexcrichton** [comment]
There's some rudimentary support for this currently but otherwise we're not currently tracking unimplemented APIs from libgit2 in this issue tracker, so I'm going to close this. PRs to add more support are of course always welcome!

**Comment by andymeneely** [comment]
Can we please document how to use what backend support is currently available? I personally would love to try to use Redis to speed up for some of my mining software repository research.

**Comment by alexcrichton** [comment]
Sorry but as with basically all open source projects keeping docs and stuff up to date isn't trivial, and there's not an overabundance of maintenance effort for this project right now. Currently you're unfortunately best of reading the source to see the support added, and if anything is missing PRs are always welcome.

**Comment by andymeneely** [comment]
Makes sense. If I can figure it out myself, I'll contribute. From the time I've spent looking at this, I don't know that it's possible at the moment.

**Comment by qaqland** [comment]
Hi, I want to add custom backend support bindings in git2 crate. Not sure when I could understand and complete it :)

**Comment by qaqland** [comment]
update:

Sorry to give up. After checking the flamegraph of my program, I found that database backend is helpless to large repositories.

![Image](https://github.com/user-attachments/assets/53b4a44d-58a6-4153-b4da-539043230719)

Parsing data to tree object takes almost the same time as to read and unpack it from local-fs. In other words, even with a database backend, under the limitations of NoSQL structure, there are still unavoidable time-consuming issues.
