### ISSUE TITLE
Creating blobs from stream

### ISSUE THREAD

**Issue by katyo** [rust-lang/git2-rs#238]
As I see the blobs can be created using files in filesystem and also binary data in memory. The libgit2 provides API to create blobs using streaming (https://libgit2.github.com/libgit2/#HEAD/group/blob/git_blob_create_fromstream).
Are bindings supports streaming feature? I would like to piping uploaded data directly to blobs without additional buffering and storing on filesystem.

**Comment by alexcrichton** [comment]
Ah I dont think these are bound yet, but no reason they couldn't be!

**Comment by katyo** [comment]
Also the libgit2 provides another way of writing blobs in streaming manner by using ODB API (https://libgit2.github.com/libgit2/#HEAD/group/odb/git_odb_open_wstream) but in this case we must know the length of stream before opening.

**Comment by katyo** [comment]
I tried to implement blobs writer. I newbie in Rust (but have experience in C and Haskell) so I maybe not fully understand some specific things. Also I not found how correctly abort stream in libgit2 documentation so I implemented commit only, but the Drop trait might be implemented too.

**Comment by katyo** [comment]
I looked in libgit2 sources and found that `free` callback of `git_writestream` is all we need to proper cleaning up uncommitted blob writing stream. So I also implemented `Drop` trait for `BlobWriter` now to complete solving this issue.

**Comment by katyo** [comment]
I implemented another way of streamed blob writing (and reading) using git [ODB](https://libgit2.github.com/libgit2/#HEAD/group/odb) APIs.

**Comment by alexcrichton** [comment]
I'm gonna close this since I think some new APIs have been bound and otherwise we're not currently tracking unbound APIs in this issue tracker.
