### ISSUE TITLE
How to push refspec with *?

### ISSUE THREAD

**Issue by AaronFriel** [rust-lang/git2-rs#242]
Pushing a refspec like `+refs/heads/*:refs/heads/*` or `+refs/heads/*` as in the following returns an error:

```rust
push.push(&["+refs/heads/*"], Some(&mut push_options))?; 
```

The error is: `'[3/-1] not a valid reference 'refs/heads/*'''`

How do I make git2 push as if it were using a push/fetch refspec as in a repository? It appears glob syntax is not obeyed as it is in the git command line.

**Comment by alexcrichton** [comment]
Heh I've always been sort of confused with how refspecs work in libgit2 as well... I sort of just randomly apply options until it works, so I'm not sure myself :(

Once figured out, though, it'd be great to include this in the docs!

**Comment by AaronFriel** [comment]
It's not clear to me, because I feel like I should be able to push using a refspec like `+refs/heads/*:refs/heads/*`, to override the destination's heads (which I think is equivalent to a `git push --all`. But it doesn't seem to work that way?

**Comment by alexcrichton** [comment]
I think that libgit2 has a gitter/slack, and maybe it'd be good to ask there?

**Comment by AaronFriel** [comment]
The gitter has had two posts since October of 2016, we will see.

**Comment by alexcrichton** [comment]
This is pretty old and is probably best for libgit2 rather than here, so I'm going to close.
