### ISSUE TITLE
Ideas to support remote helpers?

### ISSUE THREAD

**Issue by mriehl** [rust-lang/git2-rs#259]
Keybase very recently launched [encrypted git repositories](https://keybase.io/blog/encrypted-git-for-everyone) and they use a [remote helper](https://git-scm.com/docs/git-remote-helpers) (the keybase installer installs `/usr/bin/git-remote-keybase` in order to support the `keybase://` protocol).

This does not work out of the box with git2-rs, and I'm wondering if it's even possible.
I wasn't able to find any libgit documentation regarding remote helpers (resolving "something in the `$PATH` at runtime" does not sound like something a library should be doing anyway).

Do you have any idea if this is possible?

**Comment by mriehl** [comment]
I mean looking at `transport.rs` I suppose I could be doing `transport::register` but I was hoping for something a bit more "standard" (since the git remote helper is basically a standard interface to handle remotes)

**Comment by alexcrichton** [comment]
Hm could you elaborate on what you mean by something a bit more standard? AFAIK this is done through custom transports in libgit2, and the [git2-curl crate](https://github.com/alexcrichton/git2-rs/blob/master/git2-curl/src/lib.rs) should have an example of how to implement this for https. Do you mean something like an "official" `git2-keybase` crate?

**Comment by mriehl** [comment]
No, I guess what I was looking for as "standard" is a `git2-remote-helper` crate that can use the remote helper binary (could be anything since the interface is set) to provide a custom transport. This should be generic since all remote helpers must provide at least the basic features for fetch and upload-pack etc..

But from looking at the git2 curl crate it seems like it would be a lot of wrestling to implement read/write in terms of an arbitrary remote helper binary.
I can definitely see where having a specific git2-keybase crate is more library-ish because it gets rid of the runtime indirection. It just feels weird to me that `git` just works (by discovering the binary at runtime) but libgit doesn't.

**Comment by alexcrichton** [comment]
Seems plausible to me! In theory something like that could be built externally, though, right?

**Comment by kaendfinger** [comment]
This is probably more proper for another crate (or just a part of this bundle).
For reference, I did this for JGit: https://github.com/SpinlockLabs/JGit/tree/spinlock/org.eclipse.jgit/src/org/eclipse/jgit/integrate/remotehelper

**Comment by arvenil** [comment]
> For reference, I did a remote helper provider for JGit: https://github.com/SpinlockLabs/JGit/tree/spinlock/org.eclipse.jgit/src/org/eclipse/jgit/integrate/remotehelper

@kaendfinger Does this mean I can use keybase url with JGit now?

**Comment by kaendfinger** [comment]
@arvenil Sorry, nope, this means that providers that JGit supports (for example, Amazon S3) can be used with normal a normal Git client. What I implemented was the other side of the equation.

**Comment by alexcrichton** [comment]
I'm gonna close this since it's a very old issue at this point and hasn't seen a lot of action, but adding new features are always welcome through PRs!
