### ISSUE TITLE
Commit.owner() implementation

### ISSUE THREAD

**Issue by kszucs** [rust-lang/git2-rs#266]
Is it possible to implement [git_commit_owner](https://libgit2.github.com/libgit2/#HEAD/group/commit/git_commit_owner) ?

**Comment by alexcrichton** [comment]
Ah unfortunately I'm not sure that's possible to implement in this library right now. Tracking the lifetime of that object and avoiding destructors would be pretty difficult :(

**Comment by alexcrichton** [comment]
Currently tracking unimplemented APIs from libgit2 in this issue tracker, so I'm going to close this. PRs to add more support are of course always welcome!
