### ISSUE TITLE
Tree.walk() or foreach()

### ISSUE THREAD

**Issue by kszucs** [rust-lang/git2-rs#267]
However the C binding is [defined](https://github.com/alexcrichton/git2-rs/search?utf8=%E2%9C%93&q=git_tree_walk&type=) there is no Tree method to use it.

**Comment by alexcrichton** [comment]
Probably just hasn't been bound yet! PRs are of course always welcome :)

**Comment by kszucs** [comment]
I'm not that experienced with Rust yet, but I might take a try.

**Comment by alexcrichton** [comment]
Looks like this has since been implemented, so closing!
