### ISSUE TITLE
Very slow fetching (includes STR)

### ISSUE THREAD

**Issue by paulrouget** [rust-lang/git2-rs#280]
Cloning Servo from a on-disk location to the same disk takes about one minute with the git command line. With git2, it can take hours. 've attached an example. It includes a checkout of Servo, that's why it's so big (400Mb).

Download, unzip, then `cargo run --release`. You should see something like `progress: 3%. Time: 57 minutes`.

https://drive.google.com/file/d/1kWlSwahyFyZirNzqd_d6O_gtmOGoR1X3/view?usp=sharing

**Comment by alexcrichton** [comment]
I've opened an issue upstream at https://github.com/libgit2/libgit2/issues/4464, thanks for the reproduction!

**Comment by alexcrichton** [comment]
I'm going to close this in favor of the upstream issue.
