### ISSUE TITLE
How to add user name and password directly when pushing codes?

### ISSUE THREAD

**Issue by jinfagang** [rust-lang/git2-rs#285]
Hi, I am trying to implement my own git push utils which not using ssh-key, directly send username and password so that I don't need enter that everytime when pushing codes. Is there anyway to achieve that?

**Comment by alexcrichton** [comment]
@jinfagang I believe you'll use the [`credentials` callback](https://docs.rs/git2/0.6.11/git2/struct.RemoteCallbacks.html#method.credentials) and the various methods on [`Cred`](https://docs.rs/git2/0.6.11/git2/struct.Cred.html) such as [`userpass_plaintext`](https://docs.rs/git2/0.6.11/git2/struct.Cred.html#method.userpass_plaintext). Does that work for you?

**Comment by jinfagang** [comment]
So many thanks for your reply. I am actually a newbie in rust, really hope big god could indicates me some example codes, I am missed direct in git2-rs plenty apis.

**Comment by alexcrichton** [comment]
Oh sure no worries! Does this help perhaps?

https://github.com/rust-lang/crates.io/blob/master/src/git.rs#L114-L209

**Comment by jinfagang** [comment]
Thank your Sir! I will try it out!

**Comment by alexcrichton** [comment]
I'm gonna close this since I believe the question was answered!
