### ISSUE TITLE
Rust version policy?

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/git2-rs#290]
CI runs against 1.21 and stable / beta / nightly. Is that the explicit minimum Rust version for git2?

**Comment by alexcrichton** [comment]
I typically use "2 stable versions back" coupled with "add the current minimum to CI and bump it when necessary" as rules of thumb personally.

**Comment by joshtriplett** [comment]
Documented in README.md as of 718799c265d4e6fea635906cb57379a441021f3c.
