### ISSUE TITLE
First class short oids?

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/git2-rs#293]
The C side of an oid is a `char[GIT_OID_RAWSZ]`. In the various `{read,write,exists}_prefix` APIs, the oid is treated as short, with the number of set nibbles (hex chars in hex representation), eg,

```rust
impl <'repo> Odb<'repo> {
    // ...
    pub fn exists_prefix(&self, short_oid: Oid, len: usize) -> Result<Oid, Error> {
        // ...
    }
}
```

In the spirit of slice and str, it would be cleaner and rustier if the oid itself kept track of its length:

```rust
/// Unique identity of any object (commit, tree, blob, tag).
#[derive(Copy, Clone)]
pub struct Oid {
    raw: raw::git_oid,
    len: u32,
}
```

This way, the `_prefix` methods can get rid of need to pass length separately. This would be a breaking change though. :-(

It may be possible to introduce this in a non-breaking way by adding the `len` as an option, and having those functions treat length 0 as a signal to read from the oid; this would preserve behaviour for existing uses. New APIs such ODB backends could simply not have the `len` parameter.

Thoughts?

**Comment by alexcrichton** [comment]
I'd be fine with this! So long as we basically match libgit2's interface I'm down with w/e

**Comment by kamalmarhubi** [comment]
Argh, this blocks the `Deref<Target=[Oid]>` impl on `OidArray`. Great job with the debug assert on size of `Oid` there btw, wouldn't have seen that at all otherwise!

Possibilities I can see:
- add a new type for this use case
- (breaking) change the `OidArray` have an iterator with `IntoIterator<Item=Oid>` on `&OidArray`. This keeps likely use case of iterating over merge bases, and loses direct indexing.

No idea if / when you're planning on a breaking change. I saw mention in the docs on `Error::last_error`...

**Comment by alexcrichton** [comment]
I'm gonna close this for now but it'd be fine to add at any time!
