### ISSUE TITLE
Use libhttp_parser-sys crate

### ISSUE THREAD

**Issue by LeonardKoenig** [rust-lang/git2-rs#305]
Because I had many issues with the current status, I have created a bindings crate for that lib (https://github.com/LeonardKoenig/libhttp_parser-sys-rs), which doesn't do much more than creating *really* simple bindings via bindgen (many things should be blacklisted and stuff cleaned up) and building the library.

The issues boiled down to basically:
1. libhttp was installed on my system, but only for glibc and in a dynamically linked version
2. This is found by the `FIND_PACKAGE` in libgit2 and thus libgit2 doesn't try to just compile the own,
shipped files in
3. https://github.com/tailhook/vagga/ needs to be compiled statically with musl, so it cannot use said installed filed, thus resulting in a compile time (missing headers) error -- and possibly lateron link error.

Building the library via build.rs is of course better for us and more flexible.

There's much that's to be improved (see https://github.com/LeonardKoenig/libhttp_parser-sys-rs/issues/1), and I'd really like not to take over maintainership as I have no way to test things, especially on Windows and I'm just starting doing anything high-level Rust.
So if anyone wants to takeover that repo (it's unpublished as crate yet) and integrate it here, I'd be really glad.

**Comment by alexcrichton** [comment]
This sounds like a good idea to me! I don't currently have time to sort it out unfortunately, but this should definitely help with offloading some of the logic around this library in libgit2

**Comment by alexcrichton** [comment]
I'm gonna close this since I think it's an internal issue with libgit2 and we don't have a huge pressing issue to do this, but PRs are of course always welcome to do so!
