### ISSUE TITLE
`impl failure::Fail for Error?`

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/git2-rs#310]
Would you accept this change for the next breakage (together with removing `impl std::error::Error for Error`)?

**Comment by alexcrichton** [comment]
I'd probably prefer to wait for failure 1.0, but after that sounds good to me!

**Comment by alexcrichton** [comment]
Nah I'm not sure myself :(

**Comment by alexcrichton** [comment]
I'm gonna close this for now since we're still waiting for `failure`, but this can be added once its 1.0 is released.
