### ISSUE TITLE
What type of linking is used

### ISSUE THREAD

**Issue by samsieber** [rust-lang/git2-rs#323]
Since this also seems to be the repo for the git2-sys crate, could we add documentation for what linking options are available? 

I for instance, want to make sure that libgit2 and it's depdendencies are statically linked so I can just ship a binary.

I searched around and it looks like git2 might be statically linking the openssl sys crate, but I'm not sure.

**Comment by alexcrichton** [comment]
Sure yeah documentation would be great to add! Currently the default is to statically link libgit2

**Comment by promethe42** [comment]
I'm using the following command line to build a static binary:

```bash
docker run \
    --rm -it \
    -v "$(pwd)":/home/rust/src \
    -v "/home/${USER}/.cargo":/home/rust/.cargo \
    ekidd/rust-musl-builder \
    cargo build --release --target x86_64-unknown-linux-musl
```

**Comment by alexcrichton** [comment]
I'm going to close this since static by default is pretty typical for *-sys crates, but PRs to update the docs are always welcome!
