### ISSUE TITLE
Missing binding for git_remote_create_with_fetchspec

### ISSUE THREAD

**Issue by promethe42** [rust-lang/git2-rs#328]
Hi,

I want to create a remote with a specific fetchspec to avoid fetching stuff I don't need.
AFAIK `git_remote_create_with_fetchspec` has no binding.

Should I make a PR?

Regards,

**Comment by alexcrichton** [comment]
A PR would indeed be most welcome!

**Comment by alexcrichton** [comment]
I'm gonna close this since we're not currently tracking missing APIs through issues, but PRs are of course always welcome!
