### ISSUE TITLE
The result of the "statuses()" function doesn't match the output of "git status" command

### ISSUE THREAD

**Issue by xaon** [rust-lang/git2-rs#349]
Hi,

I am trying to use the following code to get a list of modified file in my git repository:

    let mut status_opt = StatusOptions::new();
    status_opt.show(StatusShow::IndexAndWorkdir);
    // status_opt.include_untracked(false).include_unmodified(false).no_refresh(false);
    let status_result = repo.statuses(Some(&mut status_opt)).unwrap();
    println!("{}", status_result.len());
    for status_entry in status_result.iter() {
        println!("{:?}", status_entry.path());
        println!("{:?}", status_entry.status());
    }

However, the above code only shows 15 of my total 40 modified files for some reason...

The command `git status -uno` show a list of 40 modified files.

I am very puzzled.

**Comment by xaon** [comment]
Seems like in order to get all `WT_MODIFIED` files correctly,  i need to set `include_untracked = true`, and then filter on the status.

So something like

    status_opt.include_untracked(true).include_unmodified(false);
    ...
    for status_entry in status_result.iter() {
        let istatus = match status_entry.status() {
            s if s.contains(git2::Status::WT_MODIFIED) => "modified: ",
            _ => continue,
        };  
    }

**Comment by alexcrichton** [comment]
Thanks for the report! This may be a more appropriate bug report though for libgit2 as we're just binding them!

**Comment by alexcrichton** [comment]
I'm going to close this since it's likely an issue with libgit2, but if a change is needed here PRs are of course always welcome!
