### ISSUE TITLE
support for multiple libgit2 versions

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/git2-rs#359]
Right now, git2-rs wraps whatever bundled copy provides, which is not 0.26 and not 0.27, but something else. This is kinda problematic for distributions which do not wish to use static linking with bundled copy.

I don't have any proposals in mind, but it seems that some project somehow support multiple versions of native libraries (through features IIUC).

**Comment by alexcrichton** [comment]
It's possible to do compile-time version detection and configure the `libgit2-sys` crate appropriately, like the `openssl-sys` crate currently does. I don't personally have time to implement that, but I can certainly review such a PR!

**Comment by alexcrichton** [comment]
I'm gonna close this since there's currently no plan to support this, but PRs are of course always welcome!
