### ISSUE TITLE
git2::Submodule::update fails with "attempt to reinitialize" even when  the "init" parameter is set to false.

### ISSUE THREAD

**Issue by VZout** [rust-lang/git2-rs#368]
If a submodule is already initialized the `git2::Submodule::update` function always returns the following even with the `init` parameter set to false: `attempt to reinitialize 'C:/Procedural-Ray-Tracing/.git/modules/deps/fmt'; class=Repository (6); code=Exists (-4)'`

Even if you deinit the submodule using the git command line tool and than call `git2::Submodule::update` with true for the `init` parameter it still gives the same error.

This is the code I'm running:

```rust
for mut sm in submodules
{
	match sm.update(false, None)
	{
		Ok(()) => (()),
		Err(e) => panic!("Update Error: {}", e),
	};
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like this may be a bug with libgit2 though perhaps?

**Comment by VZout** [comment]
That might be the case I'm not sure. I'm sorry but I don't have the time to test this currently. I'll just hack around it by using `std::process::Command` for now.

**Comment by alexcrichton** [comment]
I'm gonna close this since I think it's likely a bug with libgit2 or an issue there, and we're not tracking those issues here.
