### ISSUE TITLE
PackBuilder is missing a 'write' method

### ISSUE THREAD

**Issue by bluescreen303** [rust-lang/git2-rs#377]
Currently, `PackBuilder` has no way to write a pack + index file back to the repo.
Even though it has `write_buf`, this does not return an index and I'm not aware of different means to index packs currently.

It seems `libgit2` does have this functionality.

**Comment by alexcrichton** [comment]
Should be fine to add this binding at any time! Bindings are largely added on demand rather than exhaustively all at once

**Comment by bluescreen303** [comment]
I think the binding is there (in `libgit2-sys`) but it's not exposed on the public `PackBuilder` object.

**Comment by alexcrichton** [comment]
We're not currently tracking unimplemented APIs here in the issue tracker but PRs are of course always welcome to add more bindings!
