### ISSUE TITLE
Equivalent for git unpack-objects

### ISSUE THREAD

**Issue by sameer** [rust-lang/git2-rs#379]
Is there a way to unpack in the binding? I see that there's a pack builder, but no way to unpack.

**Comment by alexcrichton** [comment]
The source of truth is libgit2 if libgit2 has it then it's just a matter of work to get it bound here!

**Comment by sameer** [comment]
Alright, I'll look into it.

**Comment by sameer** [comment]
So it seems to be that this is [something built on top of the main capabilities of libgit](https://github.com/git/git/blob/2d3b1c576c85b7f5db1f418907af00ab88e0c303/builtin/unpack-objects.c#L484). I'll try and do a PR for this.

**Comment by sameer** [comment]
I looked into it more -- each file in the builtin folder for git is a different subcommand. 
The libgit2 equivalent needed for this, [git_packfile_unpack](https://github.com/libgit2/libgit2/blob/e6cdd17c846648aa8e1e025fa1988475886a551e/src/pack.h#L143) doesn't seem to be exposed in their [API](https://libgit2.org/libgit2/#HEAD/search/git_packfile_unpack)
 I tried adding the bindings anyways, but there are a lot of low-level structs needed, like `git_mwindow`, `git_vector` so now I'm not so sure that this can be added.

**Comment by alexcrichton** [comment]
Perhaps an upstream issue could nudge libgit2 in a particular direction?

**Comment by sameer** [comment]
That's what I'm thinking at this point. I'll open an issue on libgit2 and see what they suggest.

**Comment by alexcrichton** [comment]
I'm gonna close this issue since I think this is either an issue for libgit2 or something that we need to bind, but we're not tracking either in the issue tracker currently.
