### ISSUE TITLE
how to walk the tree

### ISSUE THREAD

**Issue by promethe42** [rust-lang/git2-rs#380]
Hi,

I'm trying to walk the entire `Tree` of a specific commit to find if a specific file was modifier by that very commit.

But AFAIK interating on a `Tree` will only give access to the first level of the tree.
Each folder is a `TreeEntry`, and I can't find a way to iterate in the entries of the folder entry.

I've seen there is now `Tree.walk()` on master.
But since there has been no release I can't use it in my project.

Please advise.

**Comment by promethe42** [comment]
I found a solution using `Repository.find_tree()`:

```rust
fn tree_has_path(path : &String, repo : &git2::Repository, tree : &git2::Tree) -> bool {
    let parts : Vec<&str> = path.split("/").collect();

    for tree_entry in tree.iter() {
        debug!("{}", tree_entry.name().unwrap());
        if tree_entry.name().unwrap() == parts[0] {
            if parts.len() == 1 {
                return true;
            } else {
                let tree = repo.find_tree(tree_entry.id()).unwrap();

                return tree_has_path(&parts[1..].join("/"), repo, &tree);
            }
        }
    }

    return false;
}
```

**Comment by alexcrichton** [comment]
That seems like it could work! There may be a more efficient and/or more native way to do this with libgit2 so it may be worthwhile asking upstream

**Comment by Weasy666** [comment]
@promethe42 did the solution you provided in your comment work for you? Maybe i didn't get what the intention was, but when i use it to check if a commit changed a file, i end up with a lot of `true` values were the commit actually didn't change the file. As tree i used `repo.find_tree(commit.tree_id())`.
It would be really great if you could help me with this.

**Comment by alexcrichton** [comment]
I'm gonna close this for now since I think this has largely been solved.
