### ISSUE TITLE
[Question] How do I (Should I?) move a `OdbReader` variable into a future?

### ISSUE THREAD

**Issue by drozdziak1** [rust-lang/git2-rs#386]
# What I'm trying to do
I'd like to use `OdbReader` to *stream* a git object to an async multipart HTTP request issued by a `ipfs-api` [method](https://docs.rs/ipfs-api/0.5.0-alpha2/ipfs_api/struct.IpfsClient.html#method.add).

# Obstacles
* The method needs `Send` while `OdbReader` is `!Send` by FFI's defaults
* The method needs `'static`

# Questions
* How do I satisfy the `'static` requirement given that `OdbReader` borrows the returning `Odb` which in turn borrows the relevant `Repository`? Arc<Mutex<OdbReader>> isn't enough because of that.
* Should I even bother trying to `unsafe impl Send for OdbReader {}`? I'm very new to FFI stuff and `libgit2`, but adding that snippet to `libgit2-sys/src/odb.rs` did not show errors in the build. However I'm worried this might be Rust just saying "I guess drozdziak1 knows what he's doing" where I clearly don't :P

Thanks!

**Comment by alexcrichton** [comment]
I don't know much about the `OdbReader` API but it may be `Send` natively, it would require verification in libgit2 that it can be sent to different threads safely.

**Comment by alexcrichton** [comment]
I think currently the answer is that you can't, and unfortunately we don't have the time to dig deeper right now, so I'm going to close. Additions to the API are always welcome through PRs!
