### ISSUE TITLE
Git Attributes Support: "git_attr_get"

### ISSUE THREAD

**Issue by Kleptine** [rust-lang/git2-rs#388]
Is there any plan for adding attribute support? Or would you take a working pull request for it?

**Comment by alexcrichton** [comment]
Just needs a PR! (I don't think anyone's currently working on it)

**Comment by Kleptine** [comment]
Sent over a PR! https://github.com/alexcrichton/git2-rs/pull/389

**Comment by aPere3** [comment]
Is there any news on #389 ? There seem to be a conflict in the merge. 

I would be very interested about having git attributes on git2-rs !

**Comment by alexcrichton** [comment]
I think it probably just needs and update and a rebase and otherwise should be good to go!

**Comment by Kleptine** [comment]
The PR is basically ready, barring a few tweaks to make the API closer to the rest of the library. You're welcome to make those tweaks if you like, or I'll probably be able to get around to it in the next couple of weeks. Swamped by work and upcoming GDC conference at the moment.

**Comment by aPere3** [comment]
Thanks for your answers! I'll see what I can do with my own schedule ;)

**Comment by alexcrichton** [comment]
I'm gonna close this since we're not using issues currently to track unimplemented APIs in libgit2, but PRs are of course always welcome to implement this!
