### ISSUE TITLE
Build failing on Windows 10

### ISSUE THREAD

**Issue by Dragonrun1** [rust-lang/git2-rs#391]
So first ran into this when trying to use a crate that depends on libgit2-sys but tracked it down to libgit2-sys
 and not the other crate. I've tried versions 0.7.9 - 0.7.11 with a couple versions of nightly and they all seem to fail at the same place as best I can tell. It seems to be failing somewhere in the build.rs stuff but that's as far as I've been able to track it down so far. I'll also say it seems to take a very long time to fail 5-10 mins.
Think I've included everything useful from a little temp test project I was using to recreate issue before the actual log messages but let me know if there's something else you need.

[log.txt](https://github.com/alexcrichton/git2-rs/files/2718795/log.txt)

**Comment by alexcrichton** [comment]
For the slowness I've unfortunately seen that MinGW compilers are often quite slow compared to other gcc compilers, and I'm not really sure why!

For the build failures it looks like the C compiler may be configured incorrectly by the libgit2-sys build script. Can you run `gcc --version` and gist that output here? I unfortunately don't have access to Windows right now so I can't easily debug this myself though :(

**Comment by Dragonrun1** [comment]
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by alexcrichton** [comment]
Ah that doesn't seem too new or too old, so I'm not really sure what's going on, sorry :(

**Comment by Dragonrun1** [comment]
Have any ideas based on the dump where I should start looking?

**Comment by alexcrichton** [comment]
You could try googling around the error message to see if anyone else is running into the same and something looks similar to your environment, but otherwise I think you'd need to start at the actual source of the error and work backwards as to why it's happening

**Comment by alexcrichton** [comment]
I'm going to close this for since this is pretty old, but if it keeps cropping up we can try to help address it.
