### ISSUE TITLE
repo clone with SSH Deploy Key fails on Windows

### ISSUE THREAD

**Issue by aphorisme** [rust-lang/git2-rs#394]
Hello there,

this might be not a problem of git2-rs, but I cannot locate it right now, so I'm hoping someone has a trail (or even a fix?) for the following. I'm running and compiling 

```
use std::path::Path;

fn main() {

    //---------------------------------
    // build up auth credentials via fetch options:
    let mut cb = git2::RemoteCallbacks::new();
    cb.credentials(|_,_,_| {
        let credentials =
            git2::Cred::ssh_key(
                "git",
                None,
                Path::new("path_to_private_key"),
                None)
            .expect("Cannot create credentials object.");
        Ok(credentials)
    });
    let mut fo = git2::FetchOptions::new();
    fo.remote_callbacks(cb);

    //---------------------------
    // Build builder
    let mut builder = git2::build::RepoBuilder::new();
    builder.fetch_options(fo);

    //-------------------
    // clone
    match builder.clone("git@github.com:someUser/someRepo.git",
                        Path::new("someRepo")) {
        Ok(_)  => println!("Cloning ok."),
        Err(e) => println!("Cloning error: {}", e),
    }
}
```

under *Fedora 28* which outputs 

```
Cloning ok.
```

and under *Windows 10* which outputs

```
Cloning error: Failed to authenticate SSH session: ; class=Ssh (23)
```

in both cases, directories are identical, there is a `path_to_private_key` file with the same private key in it, in fact,  the windows is copy from the linux directory.

What is happening here?

Thanks in advance.

**Comment by alexcrichton** [comment]
I think that unfortunately libgit2/libssh2 don't have great support for authenticating via ssh-agent on Windows. I'm not really sure what the mismatch is, but Cargo's never been able to solve this either.

**Comment by aphorisme** [comment]
I'm somewhat new to ssh/openssl/ssh-agent, despite using it quite for a while. So, this might be a silly question: Why is the ssh-agent involved here? I thought it's just a login using the private key file and "git" as the user?

**Comment by alexcrichton** [comment]
Er oops sorry, I misread and made too many assumptions!

This is indeed perplexing actually, especially if you're providing the path to the raw key this should definitely work... I suspect though that this is likely a limitation of libssh2 on Windows or something like that, perhaps some unimplemented branch somewhere?

**Comment by joshtriplett** [comment]
@aphorisme Can you try an ltrace down into the libssh library, to see which call is failing on Windows and succeeding on Linux?

**Comment by alexcrichton** [comment]
I'm gonna close this for now since it's likely a configuration issue rather than an issue with these bindings, but we can try to find time to help out if it comes up again.
