### ISSUE TITLE
Host header omits non-default port numbers

### ISSUE THREAD

**Issue by kc8apf** [rust-lang/git2-rs#405]
This was fixed in upstream libgit2 (https://github.com/libgit2/libgit2/pull/4882) but libgit2-sys's submodule is pinned to a version before that.

**Comment by bhamail** [comment]
ping. Anything I can do to help move this along?

**Comment by alexcrichton** [comment]
Thanks for the report! For updates to the submodule it's all just done through PRs, and we can update the submodule at any time!

**Comment by bhamail** [comment]
I've created PR: https://github.com/rust-lang/git2-rs/pull/421 to update the submodule.
Please let me know if more is needed.

**Comment by ehuss** [comment]
This appears to be fixed now.
