### ISSUE TITLE
Files without extension won't be ignored

### ISSUE THREAD

**Issue by Leo1003** [rust-lang/git2-rs#412]
I have a C/C++ repository to store my codes. Since unix executables usually don't have an extension and I want to ignore them. Therefore, I used the following ```.gitignore``` file. 
```
# Ignore all
*
# Unignore all with extensions
!*.*
# Unignore all dirs
!*/
```
But it seems that this library wouldn't ignore them as git would. So it didn't be recognized as a clean repository. :disappointed:

**Comment by alexcrichton** [comment]
I think this is likely a bug with libgit2 rather than this repository, so I'm going to close this. Perhaps you can open an issue over there?
