### ISSUE TITLE
Get latest commit of each repository entry

### ISSUE THREAD

**Issue by Weasy666** [rust-lang/git2-rs#414]
Is it somehow possible get the latest commit of a specific file or folder? I can't seem to find a solution for this. I want to provide a github like list of file/folder entries in a repository and want also show the latest commit that modified that file/folder. And the commits should only be from a defined branch.  
Does anybody know how to do this with git2-rs?

**Comment by Weasy666** [comment]
@alexcrichton i'm sure you are really busy, but could please maybe point me in the right direction? I would really appreciate that. Thanks in advance.

**Comment by alexcrichton** [comment]
Thanks for the ping and the issue, but currently we don't have a ton of time to help debug these sorts of questions. I'd recommend reaching out to the libgit2 repository to see if they have an answer there, and if we're missing an API here then a PR would be most welcome!
