### ISSUE TITLE
Get all tags from branch

### ISSUE THREAD

**Issue by dweidenfeld** [rust-lang/git2-rs#416]
Hi there,

I've searched for different ways to get all tags, that are created from a specific branch. This is totally possible with the Golang library, but unfortunately not with the rust version.

Normally you can search in Git for branches, that contains a specific tag-id.

Does anybody have an idea how to solve this, since core functionality is still missing in this lib?

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately we don't have a ton of time to help debug issues like this, and this library is just a thin wrapper around libgit2 so I'd recommend reaching out to upstream libgit2 authors for questions like this who may also have better materials for answering it too!
