### ISSUE TITLE
Failure authenticating SSH session

### ISSUE THREAD

**Issue by ePirat** [rust-lang/git2-rs#435]
I'm trying to use labhub (https://github.com/brndnmtthws/labhub) but I always get the
following error when it tries to (I think) clone a repo:

```
Git error: "Failed to authenticate SSH session: Unable to send userauth-publickey request"
```

Which seems to be a problem with git2-rs and / or the libssh2-sys version it uses.

**Comment by ePirat** [comment]
Turned out this was just a very misleading error message… Especially as it was caused by some bug in the past, so I spent forever debugging in that route…

**Comment by huxianglong** [comment]
Hava you solved it? I've met the same problem

**Comment by ePirat** [comment]
Yeah in my case the issue was simply a wrong hostname.
