### ISSUE TITLE
Memory errors in RebaseOptions

### ISSUE THREAD

**Issue by ehuss** [rust-lang/git2-rs#457]
There appears to be two issues in `RebaseOptions`:

- [`RebaseOptions::rewrite_notes_ref`](https://github.com/rust-lang/git2-rs/blob/c423e2b712cef58ea85a1e60f22daeb758ae48f7/src/rebase.rs#L61-L65) appears to have a dangling pointer to a temporary `CString`.  I believe what is typically done in git2 is to add an `Option<CString>` to `RebaseOptions` to hold the reference.

- [`RebaseOptions::raw`](https://github.com/rust-lang/git2-rs/blob/c423e2b712cef58ea85a1e60f22daeb758ae48f7/src/rebase.rs#L83-L95) has a call to `mem::forget` on a reference, which does nothing.  I'm not sure how this should work, since it is a little convoluted, and behaves differently from other `raw` functions, so I'm not sure why it is written the way it is.

**Comment by alexcrichton** [comment]
cc @carlosmn, I think these were introduced in #382
