### ISSUE TITLE
libgit2-sys 0.8.2 binds API from libgit2 master, not 0.28.2

### ISSUE THREAD

**Issue by jbeich** [rust-lang/git2-rs#458]
Regressed by #440

`git_url_resolve_cb` is not part of any libgit2 release from `maint/v0.28` branch. If built with `LIBGIT2_SYS_USE_PKG_CONFIG` runtime fails e.g., https://github.com/rust-lang/rust/issues/63476. Can you restore 0.28 API compatibility for libgit2-sys 0.8.3 and bump required version for libgit2-sys 0.9.0?

https://github.com/rust-lang/git2-rs/blob/4c9480afe1d2480eb4749605bcacd2fb75006ef8/libgit2-sys/build.rs#L15

**Comment by jbeich** [comment]
Given libgit2-sys 0.8.1 works fine #440 should be reverted for 0.8.3.

**Comment by alexcrichton** [comment]
The pkg-config scripts are off-by-default because there's no strong guarantee made about the libgit2 bundled version, it's opt-in and susceptible to breakage.

**Comment by jbeich** [comment]
According to semantic versioning changing public API (e.g., adding `resolve_url` to `struct git_remote_callbacks`) requires bumping minor version. This wouldn't be an issue if bundled libgit2 was only updated.
