### ISSUE TITLE
Simple cloning of a public repo fails due to authentication issues

### ISSUE THREAD

**Issue by shriphani** [rust-lang/git2-rs#463]
Here's my code, copied directly from the documentation:

```
extern crate git2;

use git2::Repository;

fn main() {
    let url = "https://github.com/india-in-data/waterways.git";
    let repo = match Repository::clone(url, "waterways") {
        Ok(repo) => repo,
        Err(e) => panic!("failed to clone: {}", e),
    };
    println!("Done")
}
```

The repo is public.

and this code fails with this error:

```
➜  git_ops git:(master) ✗ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/gitops`
thread 'main' panicked at 'failed to clone: authentication required but no callback set; class=Ssh (23)', src/main.rs:9:19
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

What am I doing wrong? This feels like I have something wrong with my setup.

**Comment by martinellison** [comment]
Does the repository require authentication? e.g. a username and password or an SSH key? The underlying C-language `libgit2` has an interface for this, but, as far as I can see, the Rust-language `git2` crate does not implement that code at writing.

**Comment by DazWilkin** [comment]
I received the same error (also on a public repo).

I realized that I've configured git to redirect `https` to `ssh`:

```bash
git config --list
url.git@github.com:.insteadof=https://github.com/
```

Rather than undo the git config, I followed the repo's example for [Cloning using SSH](https://docs.rs/git2/0.13.1/git2/build/struct.RepoBuilder.html#example) and this worked for me.

Could this have been your issue too @shriphani ?

**Comment by shriphani** [comment]
that was it. good catch. thank you very much.
