### ISSUE TITLE
Update libgit2 submodule to include case-sensitive FS fix

### ISSUE THREAD

**Issue by mersinvald** [rust-lang/git2-rs#470]
Hi, currently `libgit2` fails to build on case-sensitive file systems (like ext4) when cross-compiling for Windows.

```
cargo:warning=libgit2/src/path.c:17:10: fatal error: AclAPI.h: No such file or directory
cargo:warning= #include <AclAPI.h>
cargo:warning=          ^~~~~~~~~~
cargo:warning=compilation terminated.
```

In `libgit2` upstream there's a fix for this error already: https://github.com/libgit2/libgit2/commit/44d5e47d8c486e149c262974bfab808737ac85c1#diff-6268fdcd3d7ea1e368576fa1736e5b95

**Comment by nossralf** [comment]
This should be fixed now, I believe, as https://github.com/rust-lang/git2-rs/pull/503 has been merged.

**Comment by alexcrichton** [comment]
Yay!
