### ISSUE TITLE
Can't Set Head With Valid Hash

### ISSUE THREAD

**Issue by PrismaPhonic** [rust-lang/git2-rs#484]
I currently am unable to set head detached with a valid hash.  Here's my code:

```
    fn reset_head_to_hash(&self, hash: &[u8; 20]) -> Result<(), Error> {
        let object_id = Oid::from_bytes(hash).unwrap();

        self.repo.set_head_detached(object_id).unwrap();

        Ok(())
    }
```

When I run my program I get:

```
$ gitchain commit -m "Asdflkjadsf"          
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -3, klass: 9, message: "object not found - no match for id (0000001ead5ea3bdd8cbce5cb62063fe45d74834)" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
$ git reset --hard 0000001ead5ea3bdd8cbce5cb62063fe45d74834                                       
HEAD is now at 0000001ead Asdflkjadsf d00e9c8c
```

The hash was literally copied from the error code.  This demonstrates that it's definitely a valid hash, and I can manually set head to it, but I can't seem to set head using `set_head_detached()`.

**Comment by alexcrichton** [comment]
Thanks for the report! This looks like it's an issue with libgit2's API usage though rather than with the API bindings of this repository. In that case this is probably best an issue for libgit2 itself.
