### ISSUE TITLE
Segfault on uninitialized git global allocator

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/git2-rs#491]
The following code causes a segfault in [patch_generated_with_delta_alloc](https://github.com/libgit2/libgit2/blob/01ea911b9e14a38f94a0018c13e5f308719aced6/src/patch_generate.c#L508).

```rust
fn main() {
    git2::Patch::from_buffers(
        "abc".as_bytes(),
        None,
        "abc".as_bytes(),
        None,
        None,
    );
}
```

I believe this is because git's global allocator never gets initialized. A workaround is to add `libgit2_sys::init()` at the top of main. Should this be necessary, or should the safe git2 binding be calling init in more places?

**Comment by ehuss** [comment]
I think generally the safe `git2` side usually calls `init` from every function that needs it. The way libgit2 handles allocation was changed recently, so now a significantly larger portion of the API should be calling `init`.  

I wonder if there should be any concern about the performance impact of calling `init` everywhere.

**Comment by alexcrichton** [comment]
Yes git2 should always handle initialization. I don't think it'll be much of a performance issue but we can always handle it if it does.
