### ISSUE TITLE
Upgrade to libgit2 0.28.3

### ISSUE THREAD

**Issue by infinity0** [rust-lang/git2-rs#498]
In #483 it was observed that

>  the number of items in `git_remote_callbacks` is different, so if this is run against 0.28.3, the structure is the wrong size and nothing works.

I have confirmed that removing the `resolve_url` field from that struct is in fact the only change needed to make this current version 0.9.2 work with libgit2 0.28.3, at least in terms of getting cargo to pass its testsuite. Please do so and update the submodules, since most distros are now on 0.28.3.

**Comment by alexcrichton** [comment]
This is now done on master
