### ISSUE TITLE
Yank breaking versions with "*" deps

### ISSUE THREAD

**Issue by kornelski** [rust-lang/git2-rs#504]
An old version of `git2` has dependencies specified with `"*"` version requirement (`time = "*"`, `libgit2-sys = "*"`, `url = "*"`).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because this old version of `git2` is unusable and may cause problems for Cargo, I suggest yanking it:

```bash
cargo yank --vers 0.0.1
```

**Comment by kornelski** [comment]
Same for `libgit2-sys`


```bash
cargo yank --vers 0.0.1
```

**Comment by alexcrichton** [comment]
I don't personally have time to manage super-old versions of this crate, myself, but I'm not the only maintainer of this project!

**Comment by joshtriplett** [comment]
Seems reasonable to me. Done.
