### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by stoically** [rust-lang/git2-rs#511]
Not sure if it's in the scope of the bindings, but it would be great if git2-rs could compile to wasm32-unknown-unknown. libgit2 does compile successfully to wasm32 with clang - but in Rust world we'd probably need [support from libc](https://github.com/rust-lang/libc/issues/858) first.

On top of that libgit2 would probably need some POSIX JS emulation, like the one provided from emscripten, to actually work. Would be interesting to know whether there are already crates that push into that direction or if it'd need something completely new or maybe inspired/forked from emscripten.

**Comment by alexcrichton** [comment]
Thanks for the report! This is likely a better report for libgit2 itself though, since if that has wasm support it should be easy for us to consume it, and that's where almost all of the work is going to happen.
