### ISSUE TITLE
Pull question

### ISSUE THREAD

**Issue by sleipnir** [rust-lang/git2-rs#534]
Hello. First of all I would like to say that I think this library is incredible. But I have a doubt.
I have an application that needs to monitor a git repository and with each modification to certain .yaml files that exist in this repository I need to perform some local operations based on the content of those files that have been changed remotely.
I thought about cloning the repository with this lib and from time to time pull to download the modifications, but I would like to know if during this pull operation I would be able to identify or list the files that were changed

**Comment by alexcrichton** [comment]
Thanks for the report! I think what you'll want to do here is to pull all the changes and then iterate the history using a revwalk. I don't believe there's a way to figure out what changed while you're downloading it. If you'd like such a method though feel free to open an issue with libgit2
