### ISSUE TITLE
add and commit issues

### ISSUE THREAD

**Issue by danieleades** [rust-lang/git2-rs#561]
I'm attempting to add and commit files to a repository, and i'm producing some behaviour I don't understand.

I've created a minimal example

i'm using the following code to add and commit files to a repo-

```rust
use std::path::{Path, PathBuf};

fn main() {
    let repo_path: PathBuf = "repo".parse().unwrap();
    let file_name = "some-file";
    let repo = initialise(&repo_path);
    create_initial_commit(&repo);
    create_file(&repo_path, file_name);
    add_all(&repo);
    commit(&repo);
}

fn initialise(repo_path: &Path) -> git2::Repository {
    std::fs::create_dir(&repo_path).unwrap();
    git2::Repository::init(&repo_path).unwrap()
}

fn create_initial_commit(repo: &git2::Repository) {
    let signature = repo.signature().unwrap();
    let oid = repo.index().unwrap().write_tree().unwrap();
    let tree = repo.find_tree(oid).unwrap();
    repo.commit(
        Some("HEAD"),
        &signature,
        &signature,
        "Initial commit",
        &tree,
        &[],
    )
    .unwrap();
}

fn create_file(repo_path: &Path, file_name: &str) {
    let filepath = repo_path.join(file_name);
    std::fs::File::create(filepath).unwrap();
}

fn add_all(repo: &git2::Repository) {
    repo.index()
        .unwrap()
        .add_all(&["."], git2::IndexAddOption::DEFAULT, None)
        .unwrap();
}

fn commit(repo: &git2::Repository) {
    let mut index = repo.index().unwrap();
    let oid = index.write_tree().unwrap();
    let signature = repo.signature().unwrap();
    let parent_commit = repo.head().unwrap().peel_to_commit().unwrap();
    let tree = repo.find_tree(oid).unwrap();
    repo.commit(
        Some("HEAD"),
        &signature,
        &signature,
        "added some file",
        &tree,
        &[&parent_commit],
    )
    .unwrap();
}
```

if i then use git cli to check the status of that repo, i see the following output-

```bash
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    some-file

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        some-file
```

the file is listed as both deleted *and* untracked.

I can resolve this by either staging the untracked file (`git add some-file`), or running `git reset`.

How can i update the repo after adding the file using git2-rs such that it's consistent with the CLI?

**Comment by ehuss** [comment]
At the end of `add_all` you need to call [`index.write()`](https://docs.rs/git2/0.13.5/git2/struct.Index.html#method.write).

**Comment by danieleades** [comment]
Thanks @ehuss. Unfortunately, that doesn't seem to help

**Comment by ehuss** [comment]
Just to confirm, you added something like this?

```rust
fn add_all(repo: &git2::Repository) {
    let mut index = repo.index().unwrap();
    index
        .add_all(&["."], git2::IndexAddOption::DEFAULT, None)
        .unwrap();
    index.write().unwrap();
}
```

The in-memory contents need to be written to disk.

**Comment by danieleades** [comment]
@ehuss mea culpa, i had an `index::write_tree' rather than an `index::write`.

That seems to be the little bit of magic i was missing.

i *think* that gets me out of trouble. thankyou for the assistance!

**Comment by leontepe** [comment]
What a weird behavior. Thanks @danieleades @ehuss :-)

**Comment by SilverRainZ** [comment]
FYI, both `write_tree` and `write` are required, `write_tree` for writing a tree object and `write` for writing the index (staging area) itself.

See commit example of libgit2: https://libgit2.org/libgit2/ex/HEAD/commit.html#git_index_write-4
