### ISSUE TITLE
Repository::stash_save NULL message not supported

### ISSUE THREAD

**Issue by extrawurst** [rust-lang/git2-rs#565]
`git_stash_save` supports NULL as an optional message and will do internal logic to define a stash name.
see https://libgit2.org/libgit2/#HEAD/group/stash/git_stash_save

`git2-rs` currently does not support this behaviour.

If I were to create a PR how do you guys handle this sort of change? the *correct* api would take message as `Option<&str>` and pass null or the converted cstring. this change would break the API. is that ok?

**Comment by alexcrichton** [comment]
We have somewhat regular breaking changes here so it should be fine to change the signature. We like to batch these up though so perhaps a new method could be added for now, and that would get deleted once we have a breaking update?

**Comment by extrawurst** [comment]
sure I can create a second function for now. any schema for that when in comes to naming? `stash_save2` vs `stash_save_with_optional_message` 🙈?

**Comment by alexcrichton** [comment]
Yeah something like that I think is fine, I don't think ergonomics is necessarily the most crucial thing for this in the interim
