### ISSUE TITLE
add support for `git revert`

### ISSUE THREAD

**Issue by toxeus** [rust-lang/git2-rs#571]
Support for `git revert` seems not to be implemented yet. I couldn't find anything relevant in the docs. Also, grepping the source for libgit2's `git_revert` didn't yield any results.

I would find it useful to add support for `git revert`. Please consider adding it.

**Comment by extrawurst** [comment]
Yeah seems like it was not added yet by anyone. Would you be interested in getting your hands dirty @toxeus?

**Comment by toxeus** [comment]
Sure, I can do it. I just wanted to make sure that this was not deliberately left out for some specific reason before dedicating time to working on this feature.

**Comment by extrawurst** [comment]
the lib only contains whatever someone needed so far, so whatever is missing is only because no one cared for it yet :) looking foward to see this land 👍
