### ISSUE TITLE
Custom errors

### ISSUE THREAD

**Issue by kim** [rust-lang/git2-rs#576]
When developing custom transports, I found it a bit unsatisfying that the only way to construct a custom `git2::Error` is via `Error::from_str` -- as the code and class are very generic, it essentially always bubbles up as an "unknown error". I think this means that `transport::subtransport_action` should also call `libgit2_sys::git_error_set_str`, but if that would be the case, it would still be nice to also be able to tweak the code and class (eg. by making `Error::from_raw` public).

Would you be willing to accept a patch which does these two things?

**Comment by alexcrichton** [comment]
I don't think I'd want to stabilize `from_raw` literally as-is, but providing more constructors and/or modifiers makes sense to me!

**Comment by kim** [comment]
That makes sense, although I'm unsure where to draw the line. I've submitted a PR for the first part, and will ponder on the second for a bit.

**Comment by kim** [comment]
Closed via #577, #579, #580
