### ISSUE TITLE
Question about build.rs automatically building libgit2

### ISSUE THREAD

**Issue by maxbla** [rust-lang/git2-rs#581]
libgit2-sys' build.rs file first searches for libgit2, then if it is not found, downloads and builds libgit2. This is good because it causes the least difficulty for first-time users, but it is fraught - there isn't any way to disable this automatic building feature or any notification that it is happening. This said, I have two questions

- Why did you choose this approach - what problems exist when not automatically building libgit2?
- Should other libraries take libgit2-sys' approach?

I'm aware that many well-maintained libraries like git2-rs take a similar approach to building native libraries, but I picked git2-rs because it seems pretty popular and is maintained by at least one core rust maintainer. If this is not the proper forum for this discussion, feel free to let me know what the proper forum is and close this issue.

**Comment by ehuss** [comment]
Historically libgit2 was very unstable, and the bindings were very sensitive to the exact version being used.  Also, most systems will not have libgit2 installed.

That being said, some users use [build script overrides](https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts) to use a separately built version of libgit2.  

The approach depends heavily on the library.  I think in most cases it is nice to have the build script automatically build the library, with the option to use a system-provided library. This is often expressed with a Cargo feature, or an environment variable (the environment variable can also be used to provide a location or other options).

I would suggest for questions about best practices to try one of the user forums ([urlo](https://users.rust-lang.org/), [stackoverflow](https://stackoverflow.com/questions/tagged/rust), etc.), as you might get a broader range of responses.
