### ISSUE TITLE
List all local branches in a git dir

### ISSUE THREAD

**Issue by jpninanjohn** [rust-lang/git2-rs#582]
Question:

Is there a way to list all the local branches in a directory? 

Somethign equivalent to this command =>

`git branch --list`

I dont want remotes to be listed. Only the local branches

**Comment by ehuss** [comment]
Does the [`branches`](https://docs.rs/git2/0.13.6/git2/struct.Repository.html#method.branches) method not give you what you need?

**Comment by jpninanjohn** [comment]
Ah Yes. I didnt think of going through the docs. I only looked at the examples here in this repo. Will try it out.
