### ISSUE TITLE
[regression] recent release contains old libgit2 version

### ISSUE THREAD

**Issue by extrawurst** [rust-lang/git2-rs#596]
Hi @alexcrichton thanks for cutting a release but I think something went wrong there with the libgit2 version bundled up in the sys crate. Having a hard time to put this into words, but it surfaced on my end in `gitui` with unittests that broke *again* after they were fixed with this PR in libgit2: https://github.com/libgit2/libgit2/pull/5092

If you checkout the changes in there, you will **not** find those in the version that was released with git2-rs:
https://docs.rs/crate/libgit2-sys/0.12.8+1.0.1/source/libgit2/src/checkout.c

here is the current libgit2 version and the line that contains the fix: https://github.com/libgit2/libgit2/blob/master/src/checkout.c#L375

<img width="666" alt="image" src="https://user-images.githubusercontent.com/776816/88095259-1d475080-cb95-11ea-8f5d-24529a0ada62.png">

vs.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/776816/88095152-f12bcf80-cb94-11ea-99a8-e5dd4058924c.png">

do you have any idea how that could happen?

**Comment by extrawurst** [comment]
Here is the last `libgit2-sys` version of the file: https://docs.rs/crate/libgit2-sys/0.12.7+1.0.0/source/libgit2/src/checkout.c

This one actually contained the fix.

**Comment by extrawurst** [comment]
it is more confusing the more I dig into this. turns out this fix was never released in `libgit2`, the fix was merged into master in may, the [ticket was closed](https://github.com/libgit2/libgit2/issues/5089) and still the `1.0.1` tag does not contain this fix, as a matter of fact, the `1.0.0` also never did which makes me wonder, how this fix ever made it into the `git2-rs` version :D

Long story short, the fact that this fix is missing *now* is actually accurate, the question is why it was ever fixed in `git2-rs`

**Comment by extrawurst** [comment]
@alexcrichton I guess what I am ultimately asking for here is:

can we release & use the sys-crate again based on master like in the previous release:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/776816/88098849-b3ca4080-cb9a-11ea-9fdf-322b37397ce2.png">

**Comment by alexcrichton** [comment]
Oops sorry about that @extrawurst! I thought that we were just behind the 1.0.1 branch so I reset to 1.0.1, but I forgot that we were actually beyond 1.0.1 with changes from master. I've reset back to the master branch and republished, sorry for the runaround!

**Comment by extrawurst** [comment]
@alexcrichton no worries, thanks for the fast fix :)
