### ISSUE TITLE
impl Display for `Oid`

### ISSUE THREAD

**Issue by SirWindfield** [rust-lang/git2-rs#599]
Since `Oid`s can be represented as hex values, would you guys be OK with having them implement Display? Maybe even Debug.

On what note, I've noticed that not a lot of structs actually do derive Debug, is there a specific reason why?

**Comment by alexcrichton** [comment]
Seems reasonable to me to add!

**Comment by SirWindfield** [comment]
It actually is already part of the library. Weird that my compiler tells me that `Oid` does not implement `Debug`. But according to the docs it actually does...

Any idea why this might be the case? I do use the newest version (`0.13.8`).

**Comment by alexcrichton** [comment]
I don't know what that might mean, can you gist the error message you're receiving?

**Comment by SirWindfield** [comment]
I’ve been using sscache on my system to reduce the overall size of all of my projects as the target folders got way too big for my system (300GB+).

After deleting the cache of sscache everything compiled without errors :) I’ll close this as it works, it was just my system that didn’t resolve the crate correctly for some reason.
