### ISSUE TITLE
Ability to find a tag by name.

### ISSUE THREAD

**Issue by madelaney** [rust-lang/git2-rs#601]
All,

While using rust git2 version 0.8.13, I was trying to find a way to get a tag by name, or even being able to iterate over `git show-ref --tags` to find the tag in question.

- Mike D.

**Comment by alexcrichton** [comment]
Thanks for the report! If this is something that upstream libgit2 doesn't implement, you'll want to file an issue there. Otherwise a PR is all that's needed to bind an existing API!

**Comment by extrawurst** [comment]
you can lookup references by name: https://docs.rs/git2/0.13.8/git2/struct.Repository.html#method.reference with that you can find a tag as `refs/tags/<tag>`

**Comment by madelaney** [comment]
@extrawurst , not sure I follow. When I look at the docs for [reference](https://docs.rs/git2/0.13.8/git2/struct.Repository.html#method.reference), it says: 
> Create a new direct reference.
>
> This function will return an error if a reference already exists with the given name unless force is true, in which case it will be > overwritten.

I'm not looking to create a new reference but look up an existing how so I'm a bit confused as to how this helps?

**Comment by extrawurst** [comment]
Sorry wrong link: https://docs.rs/git2/0.13.8/git2/struct.Repository.html#method.find_reference

**Comment by madelaney** [comment]
@extrawurst , ah okay, using `find_reference`, I was able to get what I was looking for.

**Comment by extrawurst** [comment]
@madelaney you are welcome 😊
