### ISSUE TITLE
Offer $100 for seeking help on issue that git2-rs doesn't commit new file correctly in actix_web async handler

### ISSUE THREAD

**Issue by someniceone** [rust-lang/git2-rs#602]
# Ask for help with an $100 offer

I'm seeking for help for that issue with $100 offer, not very much, but hope anyone could help! Pls send me message if you can help, I will pay for that. Very appreciate it!

**I have made a project on github, you can clone and try it: https://github.com/someniceone/git2-issue**

## Issue: 
> using `git2-rs` in `async` handler of `actix_web` causes old files in git repository deleted, the reason might be that `libgit2` doesn't work well in multiple thread environment. But even the files creating do not happen at the same time, it always make the old files deleted, then only one file left at the end.  
> For example, I create file A, then file B, there should be two files A and B, but actually it deleted file A while committing file B, so only B left finally

## Target:
> It creates files through `actix_web` correctly, no old files deleting.

## Tips:
1. There is a `test_create_file` test function in `file.rs`, which try to send http call to `actix_web` handler to create files in a git `bare` repository.
2. It will make old files of git repository deleted, while it works all right if you use `create_file_then_commit_then_push` instead.
3. There is also a function `test_create_file_and_commit` in `utils.rs`, it tris to call `create_file_then_commit_then_push` from a multiple thread environment, it can't get success too.
4. It creates files in `bare` repository by using `index.add_frombuffer` and `repo.commit` of `git2-rs` 

![img](https://camo.githubusercontent.com/d4f9104ac467d8298fb9264c7e199daca2b1f0bb/68747470733a2f2f692e696d6775722e636f6d2f753158483658382e706e67)
![img1](https://camo.githubusercontent.com/fdd9ffbc7a41cc303797b775b83ea7cb12847ffa/68747470733a2f2f692e696d6775722e636f6d2f625168756f6a312e706e67)

**Comment by alexcrichton** [comment]
Thanks for the report, but I personally don't feel comfortable having bug bounties like this here on this repository. I'm going to close this as a result.

It sounds like there's definitely an bug to get fixed here somehow, but it is likely an issue with libgit2 rather than this crate, if any. I'd recommend minimizing the test case to something that doesn't require all of actix or a local project, and that should make it easier to investigate.

**Comment by someniceone** [comment]
@alexcrichton I have minimized it, would you pls take a look ? Very appreciate it! https://github.com/someniceone/git2-issue

**Comment by alexcrichton** [comment]
Sorry I don't personally have time to investigate myself, but if you'd like to file a more targeted issue with the reduction that sounds great!

**Comment by uberjay** [comment]
I noticed that someone is working on fixing various data races in libgit2! https://github.com/libgit2/libgit2/issues/5592

There are several related open PRs:

https://github.com/libgit2/libgit2/pull/5595
https://github.com/libgit2/libgit2/pull/5594
https://github.com/libgit2/libgit2/pull/5593

It seems wise to avoid multithreading with libgit2 until these issues are sorted out.

**Comment by someniceone** [comment]
@alexcrichton 
@uberjay 
Thank you both very much, my issue is fixed, the reason was I missed `index.write()` after `index.add_frombuffer()`, tho it looks like `libgit2` does have problem with multithreading, but my project works now. Thank you again!
