### ISSUE TITLE
filesystem-related nondeterminism from libgit2-sys

### ISSUE THREAD

**Issue by bmwiedemann** [rust-lang/git2-rs#618]
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that
when building below packages, there were slight differences between each build:

* bat
* cargo-c
* exa
* onefetch

from libgit2-sys
e.g. around `git_attr_get_many_with_session.cold`

My analysis showed that it is from filesystem-ordering.

I see ordering issues in the build env
/home/abuild/rpmbuild/BUILD/bat-0.15.4/target/release/build/libgit2-sys-c2cd739238a5d529/output
where .h files change order.

**Comment by alexcrichton** [comment]
Is this a bug with libgit2? Or `build.rs`? Sorry but it's not clear to me what this is a bug for at this moment

**Comment by kpcyrd** [comment]
@bmwiedemann I've very briefly looked into this (without actually reproducing it yet), can you try if this patch improves anything:
```rust
diff --git a/libgit2-sys/build.rs b/libgit2-sys/build.rs
index 178d931..f0dbbca 100644
--- a/libgit2-sys/build.rs
+++ b/libgit2-sys/build.rs
@@ -1,5 +1,6 @@
 use std::env;
 use std::fs;
+use std::io;
 use std::path::{Path, PathBuf};
 use std::process::Command;
 
@@ -199,8 +200,10 @@ fn cp_r(from: impl AsRef<Path>, to: impl AsRef<Path>) {
 }
 
 fn add_c_files(build: &mut cc::Build, path: impl AsRef<Path>) {
-    for e in path.as_ref().read_dir().unwrap() {
-        let e = e.unwrap();
+    let dir = path.as_ref().read_dir().unwrap();
+    let mut paths = dir.collect::<io::Result<Vec<_>>>().unwrap();
+    paths.sort_by_key(|e| e.path());
+    for e in paths {
         let path = e.path();
         if e.file_type().unwrap().is_dir() {
             // skip dirs for now
```

**Comment by bmwiedemann** [comment]
@kpcyrd  I tested the patch on our `bat` package and it became reproducible. Thanks. Do you want to open the PR?
