### ISSUE TITLE
revwalk.set_sorting(Sort::TIME) doesn't sort

### ISSUE THREAD

**Issue by jo-so** [rust-lang/git2-rs#636]
I'm using version 0.13.12 and this test case on a git repo fails: `cargo run |sort -c`

```rust
use git2::{
    Repository,
    Sort,
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let repo = Repository::open_from_env()?;
    let mut revwalk = repo.revwalk()?;
    revwalk.set_sorting(Sort::TIME)?;
    revwalk.push_head()?;
    for id in revwalk {
        println!("date={}", repo.find_commit(id?)?.time().seconds());
    }

    Ok(())
}

**Comment by ehuss** [comment]
It seems to work for me with `sort -rc`.  The libgit2 sort seems to be descending.

**Comment by jo-so** [comment]
Oh yes. Sorry. I'm using in my original code `author().when()` instead of `time()` which leads to a mixed timeline when using cherry-pick or rebase-i. I've validated the issue in different repos and with `commit.time()` the current version works fine.
