### ISSUE TITLE
Heads up:  possible undocumented dependency on git itself?

### ISSUE THREAD

**Issue by dunmatt** [rust-lang/git2-rs#637]
There's a lot about this that I don't know, and don't feel motivated to figure out, but I figured it may be something you'd want to know about.  

The first few times I tried to build starship (which depends on this crate) I got this error:

    error: failed to run custom build command for `libgit2-sys v0.12.14+1.1.0`

    Caused by:
      process didn't exit successfully: `/tmp/cargo-installARG7Q9/release/build/libgit2-sys-0961d48cbccb4013/build-script-build` (exit code: 127)
      --- stdout
      cargo:rerun-if-env-changed=LIBGIT2_NO_PKG_CONFIG
      cargo:rerun-if-env-changed=PKG_CONFIG
      cargo:rerun-if-env-changed=LIBGIT2_STATIC
      cargo:rerun-if-env-changed=LIBGIT2_DYNAMIC
      cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
      cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
      cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-unknown-linux-gnu
      cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_unknown_linux_gnu
      cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
      cargo:rerun-if-env-changed=PKG_CONFIG_PATH
      cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-unknown-linux-gnu
      cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_unknown_linux_gnu
      cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
      cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
      cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-unknown-linux-gnu
      cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu
      cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
      cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
      libgit2/include/git2.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2.h
      libgit2/include/git2/blame.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/blame.h
      libgit2/include/git2/stash.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/stash.h
      libgit2/include/git2/stdint.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/stdint.h
      libgit2/include/git2/refs.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/refs.h
      libgit2/include/git2/graph.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/graph.h
      libgit2/include/git2/branch.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/branch.h
      libgit2/include/git2/diff.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/diff.h
      libgit2/include/git2/cherrypick.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/cherrypick.h
      libgit2/include/git2/proxy.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/proxy.h
      libgit2/include/git2/config.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/config.h
      libgit2/include/git2/annotated_commit.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/annotated_commit.h
      libgit2/include/git2/indexer.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/indexer.h
      libgit2/include/git2/cred_helpers.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/cred_helpers.h
      libgit2/include/git2/reflog.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/reflog.h
      libgit2/include/git2/credential.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/credential.h
      libgit2/include/git2/attr.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/attr.h
      libgit2/include/git2/credential_helpers.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/credential_helpers.h
      libgit2/include/git2/worktree.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/worktree.h
      libgit2/include/git2/refdb.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/refdb.h
      libgit2/include/git2/rebase.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/rebase.h
      libgit2/include/git2/index.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/index.h
      libgit2/include/git2/odb.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/odb.h
      libgit2/include/git2/filter.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/filter.h
      libgit2/include/git2/commit.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/commit.h
      libgit2/include/git2/version.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/version.h
      libgit2/include/git2/describe.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/describe.h
      libgit2/include/git2/errors.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/errors.h
      libgit2/include/git2/blob.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/blob.h
      libgit2/include/git2/deprecated.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/deprecated.h
      libgit2/include/git2/ignore.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/ignore.h
      libgit2/include/git2/tag.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/tag.h
      libgit2/include/git2/net.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/net.h
      libgit2/include/git2/repository.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/repository.h
      libgit2/include/git2/patch.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/patch.h
      libgit2/include/git2/cert.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/cert.h
      libgit2/include/git2/types.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/types.h
      libgit2/include/git2/trace.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/trace.h
      libgit2/include/git2/apply.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/apply.h
      libgit2/include/git2/revparse.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/revparse.h
      libgit2/include/git2/submodule.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/submodule.h
      libgit2/include/git2/transaction.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/transaction.h
      libgit2/include/git2/common.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/common.h
      libgit2/include/git2/transport.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/transport.h
      libgit2/include/git2/remote.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/remote.h
      libgit2/include/git2/tree.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/tree.h
      libgit2/include/git2/clone.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/clone.h
      libgit2/include/git2/oid.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/oid.h
      libgit2/include/git2/status.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/status.h
      libgit2/include/git2/oidarray.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/oidarray.h
      libgit2/include/git2/pathspec.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/pathspec.h
      libgit2/include/git2/buffer.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/buffer.h
      libgit2/include/git2/checkout.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/checkout.h
      libgit2/include/git2/pack.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/pack.h
      libgit2/include/git2/notes.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/notes.h
      libgit2/include/git2/revwalk.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/revwalk.h
      libgit2/include/git2/object.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/object.h
      libgit2/include/git2/merge.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/merge.h
      libgit2/include/git2/refspec.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/refspec.h
      libgit2/include/git2/message.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/message.h
      libgit2/include/git2/global.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/global.h
      libgit2/include/git2/revert.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/revert.h
      libgit2/include/git2/mailmap.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/mailmap.h
      libgit2/include/git2/sys/refs.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/refs.h
      libgit2/include/git2/sys/diff.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/diff.h
      libgit2/include/git2/sys/config.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/config.h
      libgit2/include/git2/sys/openssl.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/openssl.h
      libgit2/include/git2/sys/cred.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/cred.h
      libgit2/include/git2/sys/refdb_backend.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/refdb_backend.h
      libgit2/include/git2/sys/mempack.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/mempack.h
      libgit2/include/git2/sys/reflog.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/reflog.h
      libgit2/include/git2/sys/credential.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/credential.h
      libgit2/include/git2/sys/stream.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/stream.h
      libgit2/include/git2/sys/index.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/index.h
      libgit2/include/git2/sys/filter.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/filter.h
      libgit2/include/git2/sys/commit.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/commit.h
      libgit2/include/git2/sys/hashsig.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/hashsig.h
      libgit2/include/git2/sys/repository.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/repository.h
      libgit2/include/git2/sys/path.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/path.h
      libgit2/include/git2/sys/transport.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/transport.h
      libgit2/include/git2/sys/alloc.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/alloc.h
      libgit2/include/git2/sys/merge.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/merge.h
      libgit2/include/git2/sys/odb_backend.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/sys/odb_backend.h
      libgit2/include/git2/signature.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/signature.h
      libgit2/include/git2/reset.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/reset.h
      libgit2/include/git2/odb_backend.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/odb_backend.h
      libgit2/include/git2/strarray.h => /tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include/git2/strarray.h
      TARGET = Some("aarch64-unknown-linux-gnu")
      OPT_LEVEL = Some("3")
      HOST = Some("aarch64-unknown-linux-gnu")
      CC_aarch64-unknown-linux-gnu = None
      CC_aarch64_unknown_linux_gnu = None
      HOST_CC = None
      CC = None
      CFLAGS_aarch64-unknown-linux-gnu = None
      CFLAGS_aarch64_unknown_linux_gnu = None
      HOST_CFLAGS = None
      CFLAGS = None
      CRATE_CC_NO_DEFAULTS = None
      DEBUG = Some("false")
      CARGO_CFG_TARGET_FEATURE = None
      running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "/tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include" "-I" "libgit2/src" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/pcre" "-fvisibility=hidden" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC_THRESHOLD=10" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSHA1DC_NO_STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "/tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/build/libgit2/src/apply.o" "-c" "libgit2/src/apply.c"
      running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "/tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include" "-I" "libgit2/src" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/pcre" "-fvisibility=hidden" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC_THRESHOLD=10" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSHA1DC_NO_STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "/tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/build/libgit2/src/annotated_commit.o" "-c" "libgit2/src/annotated_commit.c"
      running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "/tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/include" "-I" "libgit2/src" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/pcre" "-fvisibility=hidden" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC_THRESHOLD=10" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSHA1DC_NO_STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "/tmp/cargo-installARG7Q9/release/build/libgit2-sys-c19b2f66504291c6/out/build/libgit2/src/alloc.o" "-c" "libgit2/src/alloc.c"

      --- stderr
      qemu: Unsupported syscall: 291
      fatal: not a git repository (or any of the parent directories): .git
      **
      ERROR:/build/qemu-iYRv0n/qemu-2.11+dfsg/qom/object.c:1645:object_get_canonical_path_component: code should not be reached
    warning: build failed, waiting for other jobs to finish...
    bat /tmp/cargo-installARG7Q9/release/build/libgit2-sys-0961d48cbccb4013/build-script-build
    error: failed to compile `starship v0.47.0`, intermediate artifacts can be found at `/tmp/cargo-installARG7Q9`

Which I fixed by running `apt update && apt install git` and rebuilding.  If it matters, here's what I'm running:

    # uname -a
    Linux ip-VIRTUAL_MACHINES_IP 4.15.0-1045-aws #47-Ubuntu SMP Fri Aug 2 13:50:30 UTC 2019 aarch64 GNU/Linux

**Comment by alexcrichton** [comment]
Thanks for the report! I believe the error there though is:

```
  ERROR:/build/qemu-iYRv0n/qemu-2.11+dfsg/qom/object.c:1645:object_get_canonical_path_component: code should not be reached
```

the first bit about not being a git repository can be ignored, that's just handling submodules when this is in-repo.

**Comment by dunmatt** [comment]
Possibly... I just thought it was a git thing because installing git fixed
it...
