### ISSUE TITLE
libgit2-sys v0.12.15 fails to clone on Windows

### ISSUE THREAD

**Issue by Alovchin91** [rust-lang/git2-rs#645]
Hi,

I'm trying to use the latest `git2-rs v0.13.13` that depends on `libgit2-sys v0.12.15` and it fails to clone any repository with error 0x80000002 on Windows arm64.

It succeeds with `v0.13.12` and strict dependency on `libgit2-sys v0.12.14`.

I believe there is a change in **libgit2** that might have broken this functionality.

As I'm using Windows arm64 for development, my debugging capabilities are rather limited, but I will try to help solve this issue.

**Comment by Alovchin91** [comment]
I think I've found the culprit: https://github.com/libgit2/libgit2/issues/5745

@ehuss @alexcrichton Would it make sense to meanwhile cherry-pick the merge commit which should fix zlib for Cargo and yank git2-rs v0.13.13 and libgit2-sys v0.12.15? I'm afraid that if people will start referencing it we'll see a bunch of programs that won't work on Windows arm64.

**Comment by lhchavez** [comment]
oh boy, i don't have a lot of windows or ARM experience (and i'm only learning Rust), so if a very minimal reproduction setup can be produced and machines with some sort of debugging are available, i can probably pitch in.

a priori: i know there are some subtle differences in how loads and stores behave in x86/arm, so that may help narrow the search space (which means that more locking may be needed)

**Comment by Alovchin91** [comment]
@lhchavez I'm afraid this is complicated since there are no CI/CD or cloud virtual machines with Windows arm64 (thanks MSFT). What you probably could do is use any arm64 machine (a Raspberry Pi or an Apple Silicon Mac are possibly the most common choices) to run Windows arm64 in Qemu.

Other than that, I can offer my Surface Pro X for remote debug connection, if this is even possible via Internet.

**Comment by lhchavez** [comment]
> Now that you've mentioned loads and stores I wonder if it also fails for arm64 Linux now thinking

that last thing is what i hope, since it'll remove one unknown (Windows). i've been trying to get a RPi4 to boot with a 64-bit Ubuntu for the last two hours (and failing ^^;; probably old SD cards are to blame) to test this out since it's going to be the path of least resistance.

**Comment by Alovchin91** [comment]
I'm gonna try it on WSL 2 on that same Surface Pro X now.

**Comment by Alovchin91** [comment]
@lhchavez Yes, it also fails on WSL 2 for me: `[1]    11546 bus error`

**Comment by Alovchin91** [comment]
Hi @alexcrichton since https://github.com/rust-lang/git2-rs/pull/646 has been merged, would it be possible to yank git2-rs v0.13.13 and libgit2-sys v0.12.15 and release new versions? As mentioned in https://github.com/libgit2/libgit2/issues/5745 , it's not just about Windows arm64, but other systems are also affected, including Linux arm64 which AFAIK is Tier 1 platform. The longer those versions stay in the wild, the more software might become broken. Thanks!

**Comment by ehuss** [comment]
@Alovchin91 I'll publish a new version soon.

**Comment by alexcrichton** [comment]
I have had a moment now and went ahead and published. I'll be happy to yank the previous one if it ends up continuing to cause issues as well!

**Comment by Alovchin91** [comment]
Thanks @alexcrichton! I appreciate your response, but isn't crate being completely unusable on some platforms including Tier 1 Linux arm64 a good enough reason to yank it? 😅 Just asking, maybe not :)

**Comment by alexcrichton** [comment]
To confirm, has there been ongoing issues with this? Or  are things generally fixed?

**Comment by Alovchin91** [comment]
Yes, the latest version (v0.13.15 with libgit2-sys v0.12.17) works well for me. Thanks for the follow up! 🙂
