### ISSUE TITLE
Failed SSH authentication on Windows, success on Linux (0.13.15)

### ISSUE THREAD

**Issue by egrtechno** [rust-lang/git2-rs#659]
Given the code below I expected it to have the same behavior on Windows and Linux: sucessfully cloning a repository when you have a valid SSH key for that repository.

This succeeds on Linux (stable-x86_64-unknown-linux-gnu) but fails on Windows (stable-x86_64-pc-windows-msvc).

I have made sure that both environments contain the same SSH key. The error reported on Windows was:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -1, klass: 23, message: "Failed to 
authenticate SSH session: " }', src\main.rs:14:47
```

Given the following code:
```
use std::path::Path;

const REPO: &str = "git@github.com:rust-lang/git2-rs.git";
fn main() {
    let mut callbacks = git2::RemoteCallbacks::new();
    callbacks.credentials(git_credentials_callback);

    let mut opts = git2::FetchOptions::new();
    opts.remote_callbacks(callbacks);
    let mut builder = git2::build::RepoBuilder::new();
    builder.fetch_options(opts);
    builder.branch("master");

    builder.clone(REPO, Path::new("git2-rs")).unwrap();
}

fn git_credentials_callback(
    _url: &str,
    user_from_url: Option<&str>,
    cred_types_allowed: git2::CredentialType,
) -> Result<git2::Cred, git2::Error> {
    let user = user_from_url.unwrap();

    if cred_types_allowed.contains(git2::CredentialType::SSH_KEY) {
        let private_key = dirs::home_dir().unwrap().join(".ssh").join("id_rsa");
        let cred = git2::Cred::ssh_key(user, None, &private_key, None);
        return cred;
    }

    return Err(git2::Error::from_str("no credential option available"));
}
```

**Comment by alexcrichton** [comment]
I think this is perhaps a bug and/or feature of libgit2 itself? This crate doesn't do much other than just bind what libgit2 offers

**Comment by egrtechno** [comment]
@alexcrichton It is actually in libssh2 ... 

For anyone stumbling upon this in the future, the 'solution' (I would rather call it a workaround) is to make sure that your private key is in 'PEM' format. 
Somewhere deep inside libssh2 it calls into a function called 'libssh2_wincng_load_pem', which basically says it all. The choice what to call is dependent on a LIBCRYPT32 define. So my guess is that this code only gets included on Windows platforms hence the difference between Windows and Linux here. 

A private key starting with the following characters: `-----BEGIN OPENSSH PRIVATE KEY-----` will fail in this function. The private key file is expected to begin with:
`-----BEGIN RSA PRIVATE KEY-----`.

To convert between the two you can use ssh-keygen (-m pem option).

**Comment by alexcrichton** [comment]
Ah ok thanks for tracking that down! Perhaps a bug can be opened with libssh2 if changes in behavior are desired? Othewise I don't think there's much else do do here for git2-rs so I'm going to close this.

**Comment by darakeon** [comment]
Files generated with -m PEM are not supported by github anymore. Anyone has any other solution?
