### ISSUE TITLE
Is anywhere to make a git log like way?

### ISSUE THREAD

**Issue by phodal** [rust-lang/git2-rs#666]
I'm using git2-rs to build a Git-base tools. And now, I want to get all changes from a commits,  such as those code in  [Git Objects](http://git-scm.com/book/en/v2/Git-Internals-Git-Objects):

```
$ git log --stat 1a410e
commit 1a410efbd13591db07496601ebc7a059dd55cfe9
Author: Scott Chacon <schacon@gmail.com>
Date:   Fri May 22 18:15:24 2009 -0700

	Third commit

 bak/test.txt | 1 +
 1 file changed, 1 insertion(+)
```

And I find the C++ version of `git log` in [https://libgit2.org/libgit2/ex/HEAD/log.html](https://libgit2.org/libgit2/ex/HEAD/log.html)

It seems we need to expose ` git_commit_parent(&parent, commit, (size_t)i)` method to compare parent, then we can get the different?

But I had search code, it seems no way to do in git2-rs?

**Comment by alexcrichton** [comment]
The Rust version of that example is translated here -- https://github.com/rust-lang/git2-rs/blob/master/examples/log.rs

**Comment by phodal** [comment]
thanks
