### ISSUE TITLE
No `git_attr_value()` binding

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/git2-rs#670]
Currently the value of a git attribute can be obtained via [`Repository::get_attr()`](https://docs.rs/git2/0.13.17/git2/struct.Repository.html#method.get_attr) or [`Repository::get_attr_bytes()`](https://docs.rs/git2/0.13.17/git2/struct.Repository.html#method.get_attr_bytes), but they return `Option<&str>` or `Option<&[u8]>`, which do not tell the attribute is set to [true](https://docs.rs/libgit2-sys/0.12.18+1.1.0/libgit2_sys/fn.git_attr_value.html?search=GIT_ATTR_VALUE_TRUE), [false](https://docs.rs/libgit2-sys/0.12.18+1.1.0/libgit2_sys/constant.GIT_ATTR_VALUE_FALSE.html), [a string](https://docs.rs/libgit2-sys/0.12.18+1.1.0/libgit2_sys/constant.GIT_ATTR_VALUE_STRING.html) or [unspecified](https://docs.rs/libgit2-sys/0.12.18+1.1.0/libgit2_sys/constant.GIT_ATTR_VALUE_UNSPECIFIED.html).

`git_attr_get()` returns some [special *pointers*](https://github.com/libgit2/libgit2/blob/27e34f9b9843f7bcc33a4ccfe3e395fe303cba63/src/attr.c#L18-L34) (note that the bindings return an optional slice, but fortunately that preserves the address) to differentiate those situations, and [`git_attr_value()`](https://docs.rs/libgit2-sys/0.12.18+1.1.0/libgit2_sys/fn.git_attr_value.html) is used to obtain that information, but there's no binding to that function (https://github.com/rust-lang/git2-rs/pull/389#discussion_r266569002 looks relevant, but unfortunately it turns out that the current bindings lose informations, and the they [do not check whether the value is really a string](https://github.com/rust-lang/git2-rs/blob/455098a8a1ce24305faf690264fc5b636d210739/src/repo.rs#L984) anyway).

This is what I currently do to extract that information (feel free to copy-and-paste if it helps):
<details>

```rust
#[cfg_attr(test, derive(Debug, PartialEq))]
enum AttrValue<'a> {
    True,
    False,
    String(&'a [u8]),
    Unspecified,
}

fn attr_value(value: Option<&[u8]>) -> AttrValue<'_> {
    match unsafe { git_attr_value(value.map_or(ptr::null(), |v| v.as_ptr().cast())) } {
        GIT_ATTR_VALUE_TRUE => AttrValue::True,
        GIT_ATTR_VALUE_FALSE => AttrValue::False,
        GIT_ATTR_VALUE_STRING => AttrValue::String(value.unwrap()),
        GIT_ATTR_VALUE_UNSPECIFIED => AttrValue::Unspecified,
        _ => unreachable!(),
    }
}

#[test]
fn test_attr_value() {
    extern "C" {
        static mut git_attr__true: *const c_char;
        static mut git_attr__false: *const c_char;
        static mut git_attr__unset: *const c_char;
    }
    let attr_true = unsafe { CStr::from_ptr(git_attr__true) };
    let attr_false = unsafe { CStr::from_ptr(git_attr__false) };
    let attr_unset = unsafe { CStr::from_ptr(git_attr__unset) };
    assert_eq!(
        super::attr_value(attr_true.to_owned().as_bytes().into()),
        AttrValue::String(attr_true.to_bytes())
    );
    assert_eq!(
        super::attr_value(attr_false.to_owned().as_bytes().into()),
        AttrValue::String(attr_false.to_bytes())
    );
    assert_eq!(
        super::attr_value(attr_unset.to_owned().as_bytes().into()),
        AttrValue::String(attr_unset.to_bytes())
    );
    assert_eq!(super::attr_value(Some(b"foo")), AttrValue::String(b"foo"));
    assert_eq!(super::attr_value(attr_true.to_bytes().into()), AttrValue::True);
    assert_eq!(super::attr_value(attr_false.to_bytes().into()), AttrValue::False);
    assert_eq!(super::attr_value(attr_unset.to_bytes().into()), AttrValue::Unspecified);
    assert_eq!(super::attr_value(None), AttrValue::Unspecified);
}
```
</details>

I'm also willing to submit a pull request.

**Comment by alexcrichton** [comment]
A PR for this would be most welcome!
