### ISSUE TITLE
StatusEntry::path does not get a joinable path string

### ISSUE THREAD

**Issue by hpwxf** [rust-lang/git2-rs#687]
As I can read in https://github.com/rust-lang/git2-rs/blob/ae256db3b27dd7dedab02fa5c051bd7adedf7de7/src/status.rs#L316
`StatusEntry::path()` returns the relative path to the repository root.

Unfortunately, this path seems to always use the `/`directory separator.
Thus, on Windows (where the directory separator is `\\`), joining such a string with `Path::join()` will produce a path with both `\\` and `/`directory separators.

In my usage, I get `\\\\?\\C:\\Users\\runneradmin\\AppData\\Local\\Temp\\.tmpRy1iwp\\d1/f1` where the relative path `d1/f1` has been `join()`ed with a canonicalized path.

Is it the excepted behavior?
Is it a good idea to change the signature of `StatusEntry::path()` to return an `Option<Path>`?

**Comment by alexcrichton** [comment]
This is just binding the raw libgit2 return value, so if you'd like that to change I'd recommend opening an issue with libgit2 itself.

**Comment by hpwxf** [comment]
Ok. I will see how Windows paths are managed in libgit2 and other bindings.
