### ISSUE TITLE
foreach callbacks use GIT_EUSER instead of GIT_ERROR to stop iteration

### ISSUE THREAD

**Issue by danielzfranklin** [rust-lang/git2-rs#698]
Hi, this is a minor nitpick about an otherwise very nice library. The callbacks to `Diff::foreach` get to return false to stop iterating. It's converted to `GIT_ERROR` in `diff::binary_cb_c` and friends. This is slightly ambiguous, as libgit2 could return `GIT_ERROR` for another reason. According to [libgit2's docs](https://github.com/libgit2/libgit2/blob/508361401fbb5d87118045eaeae3356a729131aa/include/git2/errors.h#L35), `GIT_EUSER` is reserved for this sort of use case.

Would you mind a PR for this?

**Comment by alexcrichton** [comment]
Indeed, thanks!
