### ISSUE TITLE
libgit2 bump

### ISSUE THREAD

**Issue by extrawurst** [rust-lang/git2-rs#703]
can we bump up our submodule to the current libgit2 master? there is a particular merge that recently landed which a bunch of windows folks could be craving for: https://github.com/libgit2/libgit2/pull/5857

**Comment by alexcrichton** [comment]
Indeed this can happen whenever! Just needs a PR :)

**Comment by extrawurst** [comment]
> Indeed this can happen whenever! Just needs a PR :)

perfect, PR ready #704
