### ISSUE TITLE
Repository clone into not working properly with absolute windows path

### ISSUE THREAD

**Issue by Zerotask** [rust-lang/git2-rs#710]
`Repository::clone(clone_path.as_str(), "C:\\Users\\test\\Desktop\\my-project")`

is causing a panick:
```
thread 'main' panicked at 'failed to clone repository.: Error { code: -1, klass: 30, message: "path too long: \'C:/Users/test/Desktop/my-project/C:/Users/test/Desktop/my-project/...
```

Using `C:/Users/test/Desktop/my-project` or wrapping it into Path::new() will cause the same problem.

version: 0.13.19

If I drop the `C:`, then it's working.

edit: I also noticed the same error if I drop `C:`. So it's actually too long. In that case: is it possible to increase the max length?

**Comment by JMLX42** [comment]
@Zerotask did you find a workaround/fix?

@alexcrichton any chance you can steer us in the right direction to propose a fix please?

**Comment by ehuss** [comment]
Can you provide an example that fails? For me, the following works fine on Windows:

```rust
use git2::*;

fn main() {
    let repo = Repository::clone(
        "https://github.com/rust-lang/cargo.git",
        "C:\\Users\\eric\\Desktop\\cargo",
    )
    .unwrap();
}
```

Which compiler are you using?  Which version of Windows are you on?  Are there any details or information that might be unusual about your setup?

If you are cloning a repository whose path is legitimately too long, have you tried a verbatim path (like `\\?\C:\path\to\repo`)?

**Comment by JMLX42** [comment]
> Can you provide an example that fails? For me, the following works fine on Windows:

Your example does not fail.

I rebuilt my app with the *exact* same version of the crate and I cannot reproduce the issue. But since I am not the only one, there is some crate related factor at play here. Could it be a dependency that changed but the version of the crate is the same?

**Comment by JMLX42** [comment]
> I rebuilt my app with the exact same version of the crate and I cannot reproduce the issue. But since I am not the only one, there is some crate related factor at play here. 

Scratch that: I was using an older version of our own repo. If I do use the head of `master` the problem still exists. **But** the version of the `git2` crate between the working (older) and non working (newer) versions of our app are the same: `0.13.0`. So the crate is obviously affected by a dependency.

Here is the `Cargo.lock` for the older version that works: [Cargo.lock.txt](https://github.com/rust-lang/git2-rs/files/7504343/Cargo.lock.txt)

Here is the `Cargo.lock` for the newer version that does **not** work: [Cargo.lock.txt](https://github.com/rust-lang/git2-rs/files/7504338/Cargo.lock.txt)

I'll try to diff them and report back.

**Comment by JMLX42** [comment]
Here is the diff between the 2 `Cargo.toml`:

```
 diff -u Cargo.toml ../../../Downloads/gpm/Cargo.toml
--- Cargo.toml  2021-11-09 12:36:38.949275200 +0100
+++ ../../../Downloads/gpm/Cargo.toml   2021-11-09 12:25:24.669789100 +0100
@@ -1,6 +1,6 @@
 [package]
 name = "gpm"
-version = "0.15.0"
+version = "0.18.0"
 authors = ["Jean-Marc Le Roux <jeanmarc.leroux@aerys.in>"]
 edition = "2018"

@@ -23,19 +23,23 @@
 url = "2.1.1"
 tar = "0.4.26"
 flate2 = "1.0.14"
-rpassword = "4.0.5"
+rpassword = "5.0.1"
 pest = "2.1.3"
 pest_derive = "2.1.0"
 regex = "1.3.6"
-indicatif = "0.14.0"
-console = "0.10.0"
+indicatif = "0.16.2"
+console = "0.14.1"
 crypto-hash = "0.3.4"
-dirs = "2.0.2"
-semver = "0.9.0"
+dirs = "3.0.2"
+semver = "1.0.1"
 dotenv = "0.15.0"
-err-derive = "0.2.3"
-termimad = "0.8.17"
-crossterm = "0.16.0"
+err-derive = "0.3.0"
+termimad = "0.10.3"
+crossterm = "0.19.0"
+base64 = "0.13.0"
+zeroize = "1.3.0"
+openssl-probe = "0.1.4"

 [build-dependencies]
-vergen = "3.1.0"
+vergen = { version = "5.1.8", default-features = false, features = ["build"]}
+anyhow = "1.0.40"
```

**Comment by JMLX42** [comment]
So:

1. `0.13.0` in `Cargo.toml` and `0.13.20` in `Cargo.lock` => problem reproduced.
2. `0.13.20` in `Cargo.toml` and `0.13.20` in `Cargo.lock` => problem reproduced.
3. `0.13.23` in `Cargo.toml` and `0.13.23` in `Cargo.lock` => problem *not* reproduced.

So as far as I can tell upgrading to `0.13.23` and making sure `Cargo.toml` and `Cargo.lock` are in sync apparently fixes the issue.

**Comment by ehuss** [comment]
I'm going to close as it sounds like this issue is resolved.
