### ISSUE TITLE
*name_is_valid() functions

### ISSUE THREAD

**Issue by extrawurst** [rust-lang/git2-rs#714]
missing bindings for :

* [x] `git_branch_name_is_valid` (#715)
* [ ] `git_reference_name_is_valid`	
* [ ] `git_remote_name_is_valid`	
* [ ] ` git_tag_name_is_valid`

funny enough `git_remote_is_valid_name` and `git_reference_is_valid_name` is here :)

**Comment by franciscod** [comment]
trying to set these up!

**Comment by franciscod** [comment]
I'll leave the rest for somebody else to try. They're a good first PR!

**Comment by leleliu008** [comment]
is there somebody who plan to fix the rest missing bindings?

**Comment by extrawurst** [comment]
> is there somebody who plan to fix the rest missing bindings?

I think you can pick this one up - no one works on this right now

**Comment by leleliu008** [comment]
OK. let me study some rust language syntax first. then I will try to fix it.

**Comment by extrawurst** [comment]
after https://github.com/rust-lang/git2-rs/issues/734 we can at least go ahead with the branch name validity check

**Comment by sanjayts** [comment]
I was interested in fixing this so have created a PR https://github.com/rust-lang/git2-rs/pull/882 ; would appreciate some feedback on it!
