### ISSUE TITLE
vendored-openssl broken with new resolver

### ISSUE THREAD

**Issue by extrawurst** [rust-lang/git2-rs#718]
over at `gitui` a user noted that we start to see `openssl` as a dylib dependency on macos:
```
otool -L target/debug/gitui
target/debug/gitui:
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59754.100.106)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
	/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```

no the interesting part is: we use git2 via:
```
git2 = { version = "0.13", features = ["vendored-openssl"] }
```

now this worked up until now but started to stop actually vendoring (and therefore not having a dependency on openssl shared objects) since we use `resolver = "2"`.

Now I am wondering is that something about how this feature is implemented or actually a bug in the new resolver ? 😱

see https://github.com/extrawurst/gitui/issues/772#issuecomment-855476599

**Comment by extrawurst** [comment]
so I dug some more: I was wondering why **cargo** does not suffer the same issue if I enable the new resolver in there. it seems to be fixable by *pinning* the openssl crate with its `vendoring` feature on the top level (in cargo) instead of using `git2-rs`'s feature for it does the trick. The same works in gitui: https://github.com/extrawurst/gitui/issues/772#issuecomment-855892245

That is just a workaround and means the `vendored-ssl` feature is rendered useless when using the new resolver.

**Comment by alexcrichton** [comment]
Ah the fix here is relatively simple I think -- https://github.com/rust-lang/git2-rs/pull/719 -- and it's just macOS specific because the `git2` crate itself conditionally depends on `openssl-sys`, notably not on macOS

**Comment by extrawurst** [comment]
@alexcrichton ha I totally did not see that! thanks for looking into it ❤️
