### ISSUE TITLE
Repository::clone 5x slower than git clone

### ISSUE THREAD

**Issue by ZuseZ4** [rust-lang/git2-rs#729]
I tried to download enzyme directly with git clone, as well as by using the git2 crate.
git clone to an empty directory took 1:40 minutes.
git2 in release mode took 8 minutes.
The first part (including the downloading) looks similar wrt network/cpu usage.
The git2 part spends a lot of time with a single core on ~90%.

```Rust
use git2::Repository;

let url = "https://github.com/wsmoses/Enzyme";
let repo = match Repository::clone(url, "clean_foo_dir") {
    Ok(repo) => repo,
    Err(e) => panic!("failed to clone: {}", e),
};
```
I didn't expected much difference with target-cpu=native due to the libgit2 usage, but just to be sure I tested setting it in .cargo/config
```Rust
[build]
rustflags = ["-C", "target-cpu=native"]
```
I couldn't observe any impact on the performance.

git --version:
git version 2.25.1

Unfortunately I can test the git2 version only on my local pc. 
Running git clone Enzyme on a server for the first and for the second time resulted in no speed difference between both runs. 
So I guess there is no caching involved for the direct git usage.

I would have expected the default Repository::clone() method to behave identical to git clone.
Is there a difference between Repository::clone() and git clone? Did I miss something else?

**Comment by extrawurst** [comment]
A known issue in upstream: https://github.com/libgit2/libgit2/issues/4674

**Comment by ZuseZ4** [comment]
Thanks, I just looked for open issues here, not in libgit2.
Then I will try calling git directly, instead of using libgit2.
Since there's not much you can do about it we can probably close this.
