### ISSUE TITLE
git describe --dirty

### ISSUE THREAD

**Issue by hoijui** [rust-lang/git2-rs#735]
Is it possible to use the `--dirty` flag of `git describe`?
(I think not, but I might be missing something)

Would it be possible to add this?

It seems like the C version of libgit2 supports it:
https://libgit2.org/libgit2/ex/HEAD/describe.html#git_describe_options_init-1

(I would also need `--broken` and `--always` support, in the end)

**Comment by extrawurst** [comment]
the dirty suffix can be configured here: https://docs.rs/git2/0.13.20/git2/struct.DescribeFormatOptions.html#method.dirty_suffix

**Comment by hoijui** [comment]
thanks @extrawurst ! :-)
so only `--broken` is not possible I guess.. that is fine though, I can live well without that.
thank you!
