### ISSUE TITLE
OID Shortener

### ISSUE THREAD

**Issue by medwards** [rust-lang/git2-rs#737]
The [OID shortener object](https://libgit2.org/libgit2/#v0.18.0/type/git_oid_shorten) doesn't seem to be exposed. This means programs must truncate the full oid to an arbitrary length to get a 'short' SHA1.

**Comment by ArekPiekarz** [comment]
Does this method solve your issue? https://docs.rs/git2/0.13.22/git2/struct.Object.html#method.short_id

**Comment by medwards** [comment]
Ah ok, thats a good place for it.

Since that method has the most documentation on the shortening behaviour that I've seen so far I have a semi-related question: There's no way to resolve the short id once the repository grows enough that it is ambiguous, right? I was thinking that you could maybe look at the history and assume the short id is the oldest of the ambiguous commits or something, but I haven't seen anything like that elsewhere.
