### ISSUE TITLE
Getting the raw output of `git diff`

### ISSUE THREAD

**Issue by Bauxitedev** [rust-lang/git2-rs#750]
Quick question, is it somehow possible to get the raw output about of running `git diff` in the repository? As in, resulting in a large multi-line string that looks like this, for example:
```diff
diff --git a/added_file b/added_file
new file mode 100644
index 0000000..9b710f3
--- /dev/null
+++ b/added_file
@@ -0,0 +1,4 @@
+This was missing!
+Adding it now.
+
+Only for testing purposes.
```
I know there are methods like `Repository.diff_tree_to_tree()`, but that seems to wrap the output in structs and such using callbacks, but I just want the raw string itself, without any modification.

**Comment by alexcrichton** [comment]
I don't think there's a one-liner, you'll probably want to explore the [`diff` example](https://github.com/rust-lang/git2-rs/blob/master/examples/diff.rs) to see how to generate diffs.
