### ISSUE TITLE
Idiomatic way to list commits between revisions.

### ISSUE THREAD

**Issue by madelaney** [rust-lang/git2-rs#761]
All,

I was wondering how I should go about getting the changes between two revisions. I'm currently using [std::process::Command](https://doc.rust-lang.org/std/process/struct.Command.html) and parsing the output, and it works, but I feel there has to be a way to do this without having to shell out.

```rust
let output = Command::new("git")
    .arg("rev-list")
    .arg("<sha1>..<sha2>")
    .output()
    .expect("failed to execute process");
    
let stdout = String::from_utf8_lossy(&output.stdout);
for commit in stdout.split("\n") {
  // Do something here.
}
```

- Mike D.

**Comment by arxanas** [comment]
Check out the [`Revwalk`](https://docs.rs/git2/0.13.23/git2/struct.Revwalk.html) system to enumerate the commits in a certain range. You can also manually walk the parent commits (with `git2::Commit::parent`, etc.) if you have a specific situation where you know that'll work.

**Comment by madelaney** [comment]
Thanks!

I was playing aroudn with
