### ISSUE TITLE
WT_DELETED

### ISSUE THREAD

**Issue by nbari** [rust-lang/git2-rs#767]
I have a repo that keeps returning `WT_DELETED` but when doing a `git status` doesn't return anything.

any idea about how could I debug more this? ~I think~ Is because of a rename of a file (lowercase/uppercase), I am testing on macOS.

I printed the path & status and problem is that file exist in both lower and uppercase (I notice this on Github, not on the OS), how to extend the warning or check to display something like "insensitive case filesystem" etc;

**Comment by ehuss** [comment]
This perhaps sounds like an issue for https://github.com/libgit2/libgit2/issues.  libgit2 does try to honor `core.ignoreCase` (and you might want to check if setting it to `true` helps).  I believe libgit2 tries to mimic the official git client in this regard.  However, I would say libgit2 is doing the right thing, as the file really is missing.

If you want to check if the filesystem is case insensitive, I think the only way is to create two files that differ in case and see what happens. There really isn't anything this library can do (as it is intended to just be a wrapper around libgit2.)
