### ISSUE TITLE
How to update all commits in a repository?

### ISSUE THREAD

**Issue by jasontheiler** [rust-lang/git2-rs#821]
Hey there 👋 ,

I'm having difficulties figuring out how to update all commits of a given repository with this library (e.g. to update all `author` and `committer` signatures).
It seems like there is no API for [`filter-branch`](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_the_nuclear_option_filter_branch), which means I'd have to rely on `rebase` in some way or another (I guess).
I'm neither deep into Git or Rust, so I don't really understand how a non-interactive rebase should work with this library.

I haven't found any examples for this kind of usage and I'd be really greatful if someone could provide me with one.

**Comment by vincent-herlemont** [comment]
@jasontheiler Maybe is it similar to https://github.com/rust-lang/git2-rs/issues/855#issuecomment-1179514855.
