### ISSUE TITLE
Is there any case that diff_index_to_workdir return empty diff but in fact the diff exists?

### ISSUE THREAD

**Issue by swordow** [rust-lang/git2-rs#837]
I have a problem that using "git diff" in repo outputs the patch, but using git2rs's diff_index_to_workdir api does not ouput anything. Any one had this problem before? The following is the test code:

 ```
    let mut repo= git2::Repository::open(repoPath).unwrap(); // the repoPath assumed be right and unwrap always works fine
    let mut index = repo.index().unwrap();
    index.read(true); // force read, not necessray
    let mut diffOpts = DiffOptions::default();
    let diff = repo.diff_index_to_workdir(Some(&index), Some(&mut diffOpts)).unwarp();  // git diff  and assumed it has no error
    // check if contains any delfa
    if (diff.deltas().len() > 0)
    {
       //the problem is here, code  nerver runs here 
    }
    else
    {
       // always goes here and  mean that diff contains no delta
    }
```

**Comment by swordow** [comment]
Sorry for the logic bug... :-(

**Comment by leontepe** [comment]
What was your logic bug? I'm trying to implement something similar; your code is helpful.

**Comment by swordow** [comment]
> What was your logic bug? I'm trying to implement something similar; your code is helpful.

The code works fine. The previous version which was wrong is that i counted the delta num incorrectly.
