### ISSUE TITLE
Failed to add new file

### ISSUE THREAD

**Issue by swordow** [rust-lang/git2-rs#840]
I tested the ```git_index_add_bypath``` api in libgit2 and it works fine. Using ```git status``` could see the new tracked file, the following libgit2 code used:
```
#include <stdio.h>
#include <git2.h>
int main()
{
        int err = 0;
        git_repository* repo = NULL;
        git_libgit2_init();
        err = git_repository_open(&repo, "/path/to/repo");
        if (err)
        {
            printf("open repo failed\n");
            return 1;
        }
	printf("open repo ok\n");
	git_index* index = NULL;
	err = git_repository_index(&index, repo);
	if (err)
	{
		printf("get index failed!\n");
		return 1;
	}
	git_index_add_bypath(index, "relative/path/to/new/file");
	git_index_write(index);
        return 0;
}
```

But when i used git2rs, ```index.add_path``` did not give any error and the ```index.write``` was called sucessfully. But  using ```git status``` could not see the file should be added, the following code used:
```
pub fn StageAddNewFile(repoPath:&str, relativePath:&str, user:&str, email:&str)->std::result::Result<(), git2::Error>
{
    let mut ret = git2::Repository::open(repoPath);
    if ret.is_err()
    {
        println!("open repo {} failed!", repoPath);
        return std::result::Result::Err(ret.err().unwrap());
    }
    let mut repo = ret.unwrap();
    let mut index = repo.index().unwrap();
    let stagedRet = index.add_path(Path::new(&relativePath)); // relative/path/to/new/file
    if stagedRet.is_err()
    {
        println!("stage add {} failed! {}", relativePath, stagedRet.as_ref().err().unwrap().to_string());
        return std::result::Result::Err(stagedRet.err().unwrap());
    }
    let stagedRet = index.write();
    if stagedRet.is_err()
    {
        println!("stage add {}  failed! {}", relativePath, stagedRet.as_ref().err().unwrap().to_string());
        return std::result::Result::Err(stagedRet.err().unwrap());
    }
    println!("staging add new file {} ok!", relativePath);
    return std::result::Result::Ok(());
}
```
git2 version is "0.14.2"
Any help?

**Comment by ehuss** [comment]
There isn't anything immediately obvious from your code example that could be wrong (other than being written in an unusual style for Rust). You may want to double-check that you are passing the paths in that you expect, and that the added file actually has modifications.  It can help if you can put together a complete and minimal example, such as:

```rust
use std::path::Path;
use std::error::Error;
use git2::*;
use std::fs;
use std::process;

fn main() -> Result<(), Box<dyn Error>> {
    let repo = Repository::init("foo")?;
    fs::write("foo/bar", "test")?;
    let mut index = repo.index()?;
    index.add_path(Path::new("bar"))?;
    index.write()?;
    let status = process::Command::new("git").arg("status").current_dir("foo").status()?;
    assert!(status.success());
    Ok(())
}
```

Should display something like:

```
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
    new file:   bar
```

**Comment by swordow** [comment]
> There isn't anything immediately obvious from your code example that could be wrong (other than being written in an unusual style for Rust). You may want to double-check that you are passing the paths in that you expect, and that the added file actually has modifications. It can help if you can put together a complete and minimal example, such as:
> 
> ```rust
> use std::path::Path;
> use std::error::Error;
> use git2::*;
> use std::fs;
> use std::process;
> 
> fn main() -> Result<(), Box<dyn Error>> {
>     let repo = Repository::init("foo")?;
>     fs::write("foo/bar", "test")?;
>     let mut index = repo.index()?;
>     index.add_path(Path::new("bar"))?;
>     index.write()?;
>     let status = process::Command::new("git").arg("status").current_dir("foo").status()?;
>     assert!(status.success());
>     Ok(())
> }
> ```
> 
> Should display something like:
> 
> ```
> On branch master
> 
> No commits yet
> 
> Changes to be committed:
>   (use "git rm --cached <file>..." to unstage)
>     new file:   bar
> ```

Thanks. After one hour debug, i found the problem that some logic would reset the work dir after adding the file. 
The code works fine.
