### ISSUE TITLE
Missing bindings for `git_reference_symbolic_set_target`

### ISSUE THREAD

**Issue by nasso** [rust-lang/git2-rs#852]
I couldn't find bindings to the `git_reference_symbolic_set_target` function.

I am expecting a method like `git2::Reference::set_symbolic_target` that does the same as `git2::Reference::set_target` but takes a `&str` corresponding to the new target reference, just like `git_reference_symbolic_set_target` in `libgit2`.

**Comment by extrawurst** [comment]
should be easy to add. want to open a PR?

**Comment by nasso** [comment]
done :)
