### ISSUE TITLE
Edit commits during a rebase operation

### ISSUE THREAD

**Issue by vincent-herlemont** [rust-lang/git2-rs#855]
I try to edit commits with rebase operation. But I don't know to use/set `RebaseOperationType`: [src/rebase.rs#L253-L277](https://github.com/rust-lang/git2-rs/blob/db3799ad70e88262b4af05a4b4a699a104300613/src/rebase.rs#L253-L277).

I have written a quick test to check which operation [kind](https://github.com/rust-lang/git2-rs/blob/db3799ad70e88262b4af05a4b4a699a104300613/src/rebase.rs#L306) is used: `Pick` is seems set by default.

```rust
let rebase = self.repo.rebase(
    Some(&annotate_commit_branch),
    Some(&annotate_commit_upstream),
    None,None
)?;
for operation in rebase {
    let operation = operation?;
    let op_type = operation.kind();
    dbg!(op_type);
}
//  [src/repo.rs:114] op_type = Some(
//     Pick,
//  )
//  [src/repo.rs:114] op_type = Some(
//     Pick,
// )
```

I have tried another approach: set the position of the rebase iterator with `next()` and use [`rebase.commit()`](https://docs.rs/git2/latest/git2/struct.Rebase.html#method.commit).
```rust
let mut rebase = self.repo.rebase(
    Some(&annotate_commit_branch),
    Some(&annotate_commit_upstream),
    None,None
)?;
rebase.next().unwrap().unwrap();
let signature = Signature::now("test", "test")?;
rebase.commit(Some(&signature), &signature, Some("update message")).unwrap();
rebase.finish(None).unwrap();
```

But I'm stuck on this error `this patch has already been applied`:
```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -18, klass: 29, message: "this patch has already been applied" }', src/repo.rs:113:69
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1078:23
   4: ::repo::Repo::rebase
             at src/repo.rs:113:1
   5: ::main
             at src/main.rs:81:13
   6: core::ops::function::FnOnce::call_once
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Maybe I don't have the right way to approach the problem?

**Comment by extrawurst** [comment]
probably more fitting to ask in upstream `libgit2` repo

**Comment by vincent-herlemont** [comment]
@extrawurst Thanks, for your answer.

I think there is not possible to set rebase action with a custom list of operation types like `Edit` or `Squash` with `libgit2`.

An issue is opened on the upstream `libgit2` to add this feature: https://github.com/libgit2/libgit2/issues/3795.
