### ISSUE TITLE
Publish new version to crates.io

### ISSUE THREAD

**Issue by demurgos** [rust-lang/git2-rs#863]
The `git2` version in the repo is `0.15.0`, however `crates.io` only has the version `14.4`.

Could you please publish the latest version to `crates.io`? This fixes a segfault issue hit by some of my projects.

**Comment by ehuss** [comment]
Yea, I can publish the new versions soon.

**Comment by ehuss** [comment]
The new versions should be published now.

**Comment by demurgos** [comment]
Thank you very much.
