### ISSUE TITLE
question about ceiling_dirs in open_ext

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/git2-rs#892]
https://github.com/rust-lang/git2-rs/blob/ca6b3346d2e50e79d7c160cbee82ee65e2bcd701/src/repo.rs#L3456

`subdir` does not point to a git repo. Its parent directory is the repo. Why is it okay to use `subdir` as the `ceiling_dirs`?

**Comment by ehuss** [comment]
This was changed as part of https://github.com/libgit2/libgit2/commit/ed577134a5dcf30c95b740859aceebd9c1137157 to match the behavior of the git CLI. As part of [git's documentation](https://git-scm.com/docs/git#Documentation/git.txt-codeGITCEILINGDIRECTORIEScode) "It will not exclude the current working directory". There was some back-and-forth discussion about that behavior in the [original patch](https://lore.kernel.org/all/482D2F9D.4080809@viscovery.net/) that introduced this feature, and I think it boiled down to the author wanted it that way.

I agree it was a little surprising to me.

**Comment by keepsimple1** [comment]
Thanks for the info & links! I will close this issue.
