### ISSUE TITLE
please make a release with libgit2 1.6.1

### ISSUE THREAD

**Issue by 0-wiz-0** [rust-lang/git2-rs#936]
libgit2 1.6.1 has been released, which (among other fixes) contains a fix for NetBSD which particularly affects git2-rs when no system libgit2 is used (where currently the build is broken due to a conflict with system headers).
Can you please make a new release using libgit2 1.6.1 so this fix be used in other projects? Thank you.

**Comment by 0323pin** [comment]
Yes, please. This would save us a lot of issues.

**Comment by extrawurst** [comment]
there is a draft PR already: https://github.com/rust-lang/git2-rs/pull/935

**Comment by 0323pin** [comment]
Good, let's wait for it.
Right now can't update, _e.g._ `onefetch`

**Comment by sshine** [comment]
Since #935 is merged, perhaps close this issue?

**Comment by ehuss** [comment]
Indeed, thanks!
