### ISSUE TITLE
>= 0.17.0 issues running cargo semver-checks

### ISSUE THREAD

**Issue by dvzrv** [rust-lang/git2-rs#961]
Hi! I'm currently running into issues with cargo-semver-checks 0.21.0 (on Arch Linux, but can reproduce building straight from crates.io) and was asked to open a ticket here and link to [this one](https://github.com/obi1kenobi/cargo-semver-checks/issues/468).

Using git2 >= 0.17.0 cargo-semver-checks runs into TLS errors:
```
cargo semver-checks check-release
    Updating index
Error: the server did not provide a certificate; class=Ssl (16)

Caused by:
    the server did not provide a certificate; class=Ssl (16)
```

Current cargo-semver-checks 0.21.0 pulls in git2 `0.17.0` and libgit2-sys `0.15.2+1.6.4`, but only when downgrading git2 to `0.16.1` and libgit2-sys to `0.14.2+1.5.1`, the issue described in the above ticket goes away.

**Comment by dvzrv** [comment]
To give further background info:

I am packaging libgit2 for Arch Linux. It is currently at 1.6.4 and we do not apply any patches (see [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/libgit2/-/blob/c3beb8bee1d25383198ed0906c4df70350925e19/PKGBUILD)).

Our openssl in the stable repositories is at 3.0.9, soon 3.1.1 (see [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/openssl/-/blob/main/PKGBUILD)).

**Comment by ehuss** [comment]
Can you provide a reproduction that uses this crate directly? Like perhaps running the [`clone`](https://github.com/rust-lang/git2-rs/blob/master/examples/clone.rs) example? It's also important to know how which SSL backend it is using, which version, etc.
