### ISSUE TITLE
Extreme slowness on Windows

### ISSUE THREAD

**Issue by lirannl** [rust-lang/git2-rs#963]
Hi! I tried targeting windows and running my executable on a repo that's on a windows filesystem (I have Git for Windows installed), and it's running extremely slowly (>10 secs). Re-cloning the same repository on a Linux filesystem and running a linux-targeting build, runs more or less instantly.

I'm on git2 0.17.1, stable toolchain

**Comment by ehuss** [comment]
This project is just a wrapper around libgit2, so unless there seems to be something specific about the way the wrapper works, I think this is an issue for libgit2. For example, if you are trying to clone a `file://` repo, then it is likely https://github.com/libgit2/libgit2/issues/2836. If you are cloning something with a large number of deltas, then it is likely https://github.com/libgit2/libgit2/issues/4674. It might help to construct a reproducible example.

**Comment by ehuss** [comment]
I'm going to close since there isn't a reproduction here that indicates an issue with the wrapper. This is likely an upstream issue, perhaps one of those linked above.
