### ISSUE TITLE
Clone with depth

### ISSUE THREAD

**Issue by NoelJacob** [rust-lang/git2-rs#987]
It looks it's not a limitation anymore:
https://github.com/libgit2/libgit2/issues/3058#issuecomment-1540940627

_Originally posted by @RCasatta in https://github.com/rust-lang/git2-rs/issues/875#issuecomment-1564300754_

**Comment by extrawurst** [comment]
See https://github.com/rust-lang/git2-rs/pull/979

**Comment by ehuss** [comment]
Closing as resolved by #979.
